const navItems=[['home','⌂ Home'],['factions','♟ Factions'],['locations','⌖ Locations'],['clocks','◷ Clocks'],['gather','◉ Gather Information'],['complications','! Complications'],['bargains','☠ Devil’s Bargains'],['crew','♣ The Sneaks'],['npcs','♙ NPCs & Contacts'],['notes','▤ Session Notes']];
const factions=[
{name:'Gray Cloaks',status:'Friendly',tone:'good',why:'They favor The Sneaks. Origin established during crew creation; exact reason currently TBD.'},
{name:'The Wraiths',status:'Working Arrangement',tone:'good',why:'Nightmarket is their hunting ground. The Sneaks have faithfully paid tribute.'},
{name:'The Grinders',status:'Angered',tone:'bad',why:'The Sneaks stole from them.'},
{name:'The Lampblacks',status:'Undeveloped',why:'No meaningful campaign engagement yet.'},
{name:'The Crows',status:'Undeveloped',why:'No meaningful campaign engagement yet.'},
{name:'The Red Sashes',status:'Undeveloped',why:'No meaningful campaign engagement yet.'},
{name:'The Dimmer Sisters',status:'Undeveloped',why:'No meaningful campaign engagement yet.'},
{name:'The Hive',status:'Undeveloped',why:'No meaningful campaign engagement yet.'},
{name:'The Silver Nails',status:'Undeveloped',why:'No meaningful campaign engagement yet.'}
];
const complications=['Unwanted attention arrives at the worst possible moment.','The action works, but it takes longer than expected.','Someone important is put at risk.','The position worsens: the next action starts from a more dangerous place.','Evidence is left behind. Someone can connect this to the crew.','A useful resource is damaged, spent, or lost.','A faction notices what happened and takes an interest.','The success creates a new obligation or debt.','Separate the crew or cut off the easy escape route.','A clock advances because of the noise, delay, or collateral damage.','They get exactly what they wanted—plus something they really did not want.','The target learns something useful about the crew.'];
const bargains=['A rival faction learns what you are attempting.','Someone innocent will be caught in the consequences.','Advance an enemy or danger clock before the roll.','You owe a favor to someone inconvenient.','Something valuable must be left behind or sacrificed.','The job succeeds or fails, but your presence here becomes known.','A contact is endangered by helping you.','The supernatural notices you.','Your escape route will not be available afterward.','Take the extra die, but introduce a new faction interest in the score.'];
const contacts=[{name:'Quellyn',role:'Young witch',status:'Established / Trusted',info:['Occult activity','Ghosts & spirits','Rituals','Arcane ingredients','Strange artifacts','Supernatural locations'],details:'Lives in Six Towers in a cottage with a low stone fence. Her garden is mostly fungi and shade-growing things, sustained with a little magic. Drying herbs hang from the ceiling.',history:'The Sneaks completed two ingredient thefts for her admirably. Both jobs generated no Heat.'}];
const state={page:'home',rolls:JSON.parse(localStorage.getItem('doskvol-rolls')||'[]'),clocks:JSON.parse(localStorage.getItem('doskvol-clocks')||'[{"name":"Example faction clock","size":6,"filled":2}]')};
const $=s=>document.querySelector(s); const pick=a=>a[Math.floor(Math.random()*a.length)];
function head(title,sub){return `<div class="section-head"><div><h2>${title}</h2><p>${sub}</p></div></div>`}
function renderNav(){ $('#nav').innerHTML=navItems.map(([id,label])=>`<button class="navbtn ${state.page===id?'active':''}" data-page="${id}">${label}</button>`).join(''); document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()}) }
function clockHTML(c,i){return `<div class="card"><h3>${c.name}</h3><div class="clock">${Array.from({length:c.size},(_,x)=>`<button class="seg ${x<c.filled?'on':''}" data-clock="${i}" data-seg="${x}"></button>`).join('')}</div><span class="small">${c.filled} / ${c.size}</span></div>`}
function render(){renderNav();let html='';
if(state.page==='home')html=head('The City Never Sleeps','GM command centre')+`<div class="cards"><div class="card"><h3>The Sneaks</h3><p>Shadows crew operating in Doskvol.</p><span class="tag good">Quellyn: Trusted</span><span class="tag good">Wraith tribute paid</span><span class="tag bad">Grinders angered</span></div><div class="card"><h3>Tonight's Quick Tools</h3><p>Roll a d6, draw a complication or Devil's Bargain from the rail. Everything here is designed for one-tap use during play.</p></div><div class="card"><h3>Campaign Memory</h3><p>Faction relationships, contacts, clocks and locations will accumulate here as the campaign changes.</p></div></div>`;
if(state.page==='factions')html=head('Factions','Power moves in a broken city')+`<input id="factionSearch" class="search" placeholder="Search factions or relationships…"><div id="factionCards" class="cards">${factions.map(f=>`<div class="card faction"><h3>${f.name}</h3><span class="tag ${f.tone||''}">${f.status}</span><p>${f.why}</p></div>`).join('')}</div>`;
if(state.page==='locations')html=head('Locations','Know the city. Use the city.')+`<div class="map-placeholder"><div><strong>DOSKVOL CITY MAP</strong><p>Your supplied game map will become the base layer here.</p><p class="small">Planned: pan/zoom · district selection · Quellyn's cottage · faction territory overlays · contested areas · location clocks</p></div></div><div class="cards" style="margin-top:12px"><div class="card"><h3>Six Towers · Quellyn's Cottage</h3><p>Small stone-fenced garden, mostly fungi and shade-growing plants. A little magic keeps things going. Drying herbs hang throughout the cottage.</p><span class="tag good">Known location</span></div></div>`;
if(state.page==='clocks')html=head('Clocks','What is moving while the crew acts?')+`<button id="addClock">+ Add Clock</button><div class="cards" style="margin-top:12px">${state.clocks.map(clockHTML).join('')}</div>`;
if(state.page==='gather')html=head('Gather Information','Who do you know—and what do they know?')+contacts.map(c=>`<div class="card contact"><div><h3>${c.name} · ${c.role}</h3><span class="tag good">${c.status}</span><p>${c.details}</p><p><b>Useful for:</b> ${c.info.join(' · ')}</p><div class="note"><b>History:</b> ${c.history}</div></div><div><button id="quellLead">Ask for a lead</button></div></div>`).join('')+`<div id="lead" class="note" style="display:none"></div><p class="small">Other playbook contacts will be added as undeveloped contacts: personalities and information niches can grow through play.</p>`;
if(state.page==='complications')html=head('Complications','Twists for success at a cost')+`<div class="cards">${complications.map((x,i)=>`<div class="card"><h3>${i+1}</h3><p>${x}</p></div>`).join('')}</div>`;
if(state.page==='bargains')html=head("Devil's Bargains",'More power. A higher price.')+`<div class="cards">${bargains.map((x,i)=>`<div class="card"><h3><span class="devil">☠</span> ${i+1}</h3><p>${x}</p></div>`).join('')}</div>`;
if(state.page==='crew')html=head('The Sneaks','Shadows in Doskvol')+`<div class="cards"><div class="card"><h3>Crew</h3><p>Shadows. Their campaign relationships and score history will live here.</p></div><div class="card"><h3>Established threads</h3><p>Quellyn · two clean ingredient thefts<br>Wraiths · faithful Nightmarket tribute<br>Grinders · angered after theft<br>Gray Cloaks · friendly, origin TBD</p></div></div>`;
if(state.page==='npcs')html=head('NPCs & Contacts','People remember what the crew does')+`<div class="cards"><div class="card"><h3>Quellyn the Witch</h3><span class="tag good">Established / Trusted</span><p>Young witch · Six Towers</p><p>${contacts[0].details}</p></div></div>`;
if(state.page==='notes')html=head('Session Notes','Catch it before it disappears')+`<div class="card"><textarea id="notes" class="search" rows="14" placeholder="Type GM notes here…">${localStorage.getItem('doskvol-notes')||''}</textarea><p class="small">Saved automatically on this device.</p></div>`;
$('#main').innerHTML=html; wirePage();}
function wirePage(){let s=$('#factionSearch');if(s)s.oninput=()=>document.querySelectorAll('.faction').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(s.value.toLowerCase())?'':'none');let a=$('#addClock');if(a)a.onclick=()=>{let name=prompt('Clock name?');if(!name)return;let size=Number(prompt('Segments? 4, 6, or 8','6'));if(![4,6,8].includes(size))size=6;state.clocks.push({name,size,filled:0});saveClocks();render()};document.querySelectorAll('[data-clock]').forEach(b=>b.onclick=()=>{let c=state.clocks[+b.dataset.clock];let seg=+b.dataset.seg;c.filled=seg<c.filled?seg:seg+1;saveClocks();render()});let q=$('#quellLead');if(q)q.onclick=()=>{let lead=pick(['Quellyn has heard of an occult ingredient changing hands quietly in Six Towers. Someone will pay to have it intercepted.','A spirit has been repeating the same name near an abandoned property. Quellyn thinks there is a reason—and possibly something worth stealing.','A wealthy collector has acquired an arcane object Quellyn recognizes. She does not want it destroyed. She wants it removed without anyone knowing who took it.']);$('#lead').style.display='block';$('#lead').innerHTML='<b>Quellyn suggests:</b> '+lead};let n=$('#notes');if(n)n.oninput=()=>localStorage.setItem('doskvol-notes',n.value)}
function saveClocks(){localStorage.setItem('doskvol-clocks',JSON.stringify(state.clocks))}
function renderHistory(){ $('#rollHistory').textContent=state.rolls.length?'Recent: '+state.rolls.slice(0,6).join(' · '):'No rolls yet.' }
$('#rollDie').onclick=()=>{let d=$('#die');d.classList.remove('rolling');void d.offsetWidth;d.classList.add('rolling');let r=1+Math.floor(Math.random()*6);setTimeout(()=>{d.textContent=r;state.rolls.unshift(r);state.rolls=state.rolls.slice(0,20);localStorage.setItem('doskvol-rolls',JSON.stringify(state.rolls));renderHistory()},300)};
$('#rollComplication').onclick=()=>$('#complication').textContent=pick(complications);$('#rollBargain').onclick=()=>$('#bargain').textContent=pick(bargains);render();renderHistory();
