const navItems=[['home','⌂ Ledger'],['oracle','◈ Action Oracle'],['factions','♟ Factions'],['locations','⌖ City Map'],['clocks','◷ Clocks'],['npcs','♙ Faces'],['gather','◉ Gather Info'],['score','⚔ Score Engine'],['crew','♣ The Sneaks'],['notes','▤ Session Notes']];
const baseFactions=[
{name:'Gray Cloaks',status:2,label:'Friendly',tone:'good',why:'They favor The Sneaks. The original reason was established during crew creation but remains deliberately undefined.',face:'Morrow Vey',faceRole:'Gray Cloak fixer',personality:'Polite, severe, and impossible to hurry. Speaks as if every favor has already been entered in a ledger.',want:'Quiet leverage over people who once wore the Bluecoat badge.'},
{name:'The Wraiths',status:1,label:'Working Arrangement',tone:'good',why:'They use Nightmarket as a hunting ground. The Sneaks have faithfully paid tribute.',face:'Silas Veil',faceRole:'Tribute collector',personality:'Never raises his voice. Smiles when others lie and becomes friendlier when threatened.',want:'Proof that The Sneaks understand who owns the shadows in Nightmarket.'},
{name:'The Grinders',status:-2,label:'Angered',tone:'bad',why:'The Sneaks stole from them.',face:'Rusk Havel',faceRole:'Grinder enforcer',personality:'Blunt, patriotic, and patient enough to make revenge feel inevitable rather than emotional.',want:'Restitution, humiliation, or a useful betrayal.'},
{name:'The Lampblacks',status:0,label:'Undeveloped',why:'No meaningful campaign engagement yet.',face:'Mira Cask',faceRole:'Lampblack broker',personality:'Warm laugh, cold eyes. Treats crime like tavern gossip until money is mentioned.',want:'Reliable people who can hurt rivals without attracting Bluecoats.'},
{name:'The Crows',status:0,label:'Undeveloped',why:'No meaningful campaign engagement yet.',face:'Bellweather',faceRole:'Crow lookout-master',personality:'Restless and superstitious; taps twice on wood before giving bad news.',want:'Advance warning whenever Crow’s Foot is about to erupt.'},
{name:'The Red Sashes',status:0,label:'Undeveloped',why:'No meaningful campaign engagement yet.',face:'Sera Vellis',faceRole:'Red Sash liaison',personality:'Elegant, disciplined, cuttingly observant. Compliments are often tests.',want:'Competence, discretion, and proof that crude force is not the crew’s only tool.'},
{name:'The Dimmer Sisters',status:0,label:'Undeveloped',why:'No meaningful campaign engagement yet.',face:'Aunt Mourning',faceRole:'Occult intermediary',personality:'Soft-spoken, maternal, and deeply unsettling. Answers questions with questions that become true later.',want:'Small impossible objects and people willing to carry them.'},
{name:'The Hive',status:0,label:'Undeveloped',why:'No meaningful campaign engagement yet.',face:'Orlan Pike',faceRole:'Commercial agent',personality:'Immaculate coat, clipped diction, no visible sense of humor. Always knows the market price.',want:'Predictability and profit.'},
{name:'The Silver Nails',status:0,label:'Undeveloped',why:'No meaningful campaign engagement yet.',face:'Captain Esme Rook',faceRole:'Mercenary outrider',personality:'Direct, dry, and respectful of nerve. Hates mystical posturing but respects real occult danger.',want:'Useful intelligence about ghosts, routes, and hostile supernatural territory.'}
];
const districts=[
['Whitecrown','Power, estates, institutions.','High'],['Brightstone','Old money, luxury, polished danger.','High'],['Charterhall','Civic offices, commerce, respectable corruption.','High'],['Six Towers','Faded wealth, haunted mansions, quiet rot.','Medium'],['Silkshore','Pleasure, art, vice, spectacle.','Medium'],['Nightmarket','Rail trade, strange goods, illicit commerce.','Medium'],["Crow’s Foot",'Stacked streets, gang turf, volatile borders.','Low'],['The Docks','Warehouses, taverns, sailors, violence.','Low'],['Barrowcleft','Markets, farms, eeleries, working families.','Medium'],['Coalridge','Factories, soot, labor, old industry.','Low'],['Charhollow','Crowded tenements and hard lives.','Low'],['Dunslough','Prison labor, poverty, desperation.','Low']
];
const npcSeeds=[
{name:'Quellyn',role:'Young witch',kind:'Trusted contact',district:'Six Towers',canon:true,voice:'Curious, quick, quietly intense. She gets distracted by strange details and then snaps back with unnerving precision.',tell:'Absent-mindedly sorts herbs, bones, or chalk while talking.',want:'Rare ingredients, occult answers, and people who do not panic around the supernatural.',history:'The Sneaks completed two ingredient thefts for her admirably. Both jobs generated no Heat.',details:'Lives in a Six Towers cottage behind a low stone fence. Her garden is mostly fungi and things suited to Doskvol, helped along by a little genuine magic. Drying herbs hang from the ceiling.'},
...baseFactions.map(f=>({name:f.face,role:f.faceRole,kind:f.status<0?'Enemy / pressure':'Faction contact',district:'—',canon:false,voice:f.personality,tell:'Campaign-created personality seed.',want:f.want,history:`Linked to ${f.name}.`,details:`Use as the speaking face of ${f.name} until play establishes someone better.`}))
];
const complications=['Unwanted attention arrives at the worst possible moment.','The action works, but it takes longer than expected.','Someone important is put at risk.','The position worsens for the next action.','Evidence is left behind that can point toward the crew.','A useful resource is damaged, spent, or lost.','A faction notices and takes an interest.','The success creates a new obligation or debt.','The crew is separated or the easy escape route closes.','A clock advances because of noise, delay, or collateral damage.','The target learns something useful about the crew.','Reduced effect: they get less than they hoped for.'];
const bargains=['A rival faction learns what you are attempting.','Someone innocent will be caught in the consequences.','Tick an enemy or danger clock before the roll.','You owe a favor to someone inconvenient.','Something valuable must be sacrificed.','Your presence becomes known regardless of the roll.','A contact is endangered by helping you.','The supernatural notices you.','Your escape route will not be available afterward.','Take +1d, but a faction gains a reason to care about this score.'];
const scoreHooks=['A locked-room theft during a funeral wake.','A rail cargo changes hands for three minutes in Nightmarket.','A ruined Six Towers manor has one lit window.','A Grinder courier is carrying something worth more than his life.','A Bluecoat evidence wagon takes the same route every third bell.','An occult collector wants an object stolen intact—and refuses to say why.'];
const state={page:'home',rolls:JSON.parse(localStorage.getItem('doskvol-rolls')||'[]'),clocks:JSON.parse(localStorage.getItem('doskvol-clocks')||'[{"name":"Grinders retaliate","size":6,"filled":2},{"name":"Wraith suspicion","size":4,"filled":0}]'),factionStatus:JSON.parse(localStorage.getItem('doskvol-faction-status')||'{}')};
const $=s=>document.querySelector(s), pick=a=>a[Math.floor(Math.random()*a.length)], esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function head(t,s){return `<div class="section-head"><div><p class="eyebrow">THE HAUNTED CITY</p><h2>${t}</h2><p>${s}</p></div><div class="ornament">☾ ✦ ☽</div></div>`}
function renderNav(){ $('#nav').innerHTML=navItems.map(([id,label])=>`<button class="navbtn ${state.page===id?'active':''}" data-page="${id}">${label}</button>`).join(''); document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});}
function clockHTML(c,i){return `<div class="card clock-card"><h3>${esc(c.name)}</h3><div class="clock">${Array.from({length:c.size},(_,x)=>`<button class="seg ${x<c.filled?'on':''}" data-clock="${i}" data-seg="${x}" aria-label="set clock to ${x+1}"></button>`).join('')}</div><span class="small">${c.filled} / ${c.size}</span><button class="ghost-btn" data-delclock="${i}">Remove</button></div>`}
function factionCard(f,i){let st=state.factionStatus[f.name]??f.status;let tone=st>0?'good':st<0?'bad':'';return `<div class="card faction" data-faction-card><div class="card-rune">♟</div><h3>${f.name}</h3><span class="tag ${tone}">Status ${st>0?'+':''}${st}</span><p>${f.why}</p><div class="npc-strip"><b>${f.face}</b> · ${f.faceRole}<br><span>${f.personality}</span></div><div class="status-controls"><button data-faction="${i}" data-delta="-1">−</button><button data-faction="${i}" data-delta="1">+</button></div></div>`}
function rollPool(n){if(n<=0){let a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);return {dice:[a,b],result:Math.min(a,b),critical:false,zero:true};}let dice=Array.from({length:n},()=>1+Math.floor(Math.random()*6));let result=Math.max(...dice);return {dice,result,critical:dice.filter(x=>x===6).length>=2,zero:false};}
function interpret(position,effect,r){let effTicks={limited:1,standard:2,great:3}[effect];let outcome='',consequence='',cls='';if(r.critical){outcome='Critical success';consequence='Exceptional result. Consider increased effect or an added benefit.';cls='good';}else if(r.result===6){outcome='Full success';consequence='They do it cleanly at the chosen effect.';cls='good';}else if(r.result>=4){outcome='Success with consequence';cls='mixed';consequence=position==='controlled'?'Minor consequence, reduced effect, or a small complication.':position==='risky'?'A real consequence: harm, complication, reduced effect, lost opportunity, or worse position.':'A severe consequence appropriate to a desperate position.';}else{outcome='Bad outcome';cls='bad';consequence=position==='controlled'?'They can withdraw or press on from a riskier position; use a minor consequence if appropriate.':position==='risky'?'Things go badly: serious consequence, lost opportunity, or dangerous escalation.':'The worst comes to pass: severe consequence, major complication, or serious harm.';}return {outcome,consequence,effTicks,cls};}
function render(){renderNav();let html='';
if(state.page==='home')html=head('The Black Ledger','A one-screen memory palace for your campaign')+`<div class="hero-grid"><div class="card hero-card"><div class="card-rune">♣</div><h3>The Sneaks</h3><p>Shadows crew moving through Doskvol with a trusted witch, paid Wraith tribute, friendly Gray Cloaks, and angry Grinders.</p><div><span class="tag good">Quellyn trusted</span><span class="tag good">Wraith arrangement</span><span class="tag bad">Grinders angry</span></div><button class="primary" data-jump="oracle">Resolve the next action</button></div><div class="card"><h3>Pressure Tonight</h3><p><b>Grinders retaliate:</b> ${state.clocks[0]?.filled||0}/${state.clocks[0]?.size||6}</p><p><b>Best immediate hook:</b> ${pick(scoreHooks)}</p><button id="newHook">Draw another hook</button><div id="hook"></div></div></div><div class="cards"><div class="card"><h3>GM Rhythm</h3><p>Ask the goal → choose action → set position → set effect → add bonus dice → roll → follow the fiction.</p></div><div class="card"><h3>Campaign Memory</h3><p>Faction standing, clocks, notes, and recent rolls persist on this device.</p></div><div class="card"><h3>Map Desk</h3><p>Use the interactive district chart for fast atmosphere and score prompts, then open the official Player Kit for the detailed city map.</p><button data-jump="locations">Open city desk</button></div></div>`;
if(state.page==='oracle')html=head('Action Oracle','Position · effect · pips · outcome')+`<div class="oracle-layout"><div class="card oracle-controls"><h3>1. How dangerous is it?</h3><div class="choice-row" id="positions">${['controlled','risky','desperate'].map((x,i)=>`<button class="choice ${i===1?'selected':''}" data-pos="${x}">${x}</button>`).join('')}</div><h3>2. How much can they accomplish?</h3><div class="choice-row" id="effects">${['limited','standard','great'].map((x,i)=>`<button class="choice ${i===1?'selected':''}" data-eff="${x}">${x}</button>`).join('')}</div><h3>3. Action pips / dice</h3><div class="pip-row" id="pips">${[0,1,2,3,4,5,6].map((x,i)=>`<button class="pip ${i===1?'selected':''}" data-pips="${x}">${x}</button>`).join('')}</div><div class="bonus-line"><label><input type="checkbox" id="bonusAssist"> Assist +1d</label><label><input type="checkbox" id="bonusPush"> Push / Bargain +1d</label></div><button id="resolveAction" class="primary big">ROLL & RESOLVE</button></div><div class="card oracle-result" id="oracleResult"><div class="oracle-sigil">◈</div><h3>Ready</h3><p>Choose the situation, set their pips, and let the oracle handle the dice.</p></div></div><div class="rule-strip"><b>Effect clock ticks:</b> Limited 1 · Standard 2 · Great 3. Default action position is Risky.</div>`;
if(state.page==='factions')html=head('Faction Ledger','Friends, rivals, debts, and people who speak for them')+`<input id="factionSearch" class="search" placeholder="Search faction, person, relationship…"><div id="factionCards" class="cards">${baseFactions.map(factionCard).join('')}</div>`;
if(state.page==='locations')html=head('City Map Desk','Click a district to turn geography into play')+`<div class="map-grid"><div class="gothic-map">${districts.map((d,i)=>`<button class="district d${i}" data-district="${i}">${d[0]}</button>`).join('')}<div class="river">DOSK RIVER</div><div class="map-compass">N<br>✦</div></div><div class="card" id="districtInfo"><h3>Select a district</h3><p>Tap any district for atmosphere, wealth, and a score seed.</p></div></div><div class="map-actions"><a class="button-link" href="https://bladesinthedark.com/downloads" target="_blank" rel="noopener">Open official Player Kit map ↗</a></div><div class="cards"><div class="card"><h3>Known · Quellyn’s Cottage</h3><p>Six Towers. Low stone fence, strange garden, fungi and shade-grown things sustained by a little magic; drying herbs inside.</p></div><div class="card"><h3>Map Use</h3><p>This schematic is deliberately an original play aid, not a copied street map. Use it for district selection and jump to the official map for detail.</p></div></div>`;
if(state.page==='clocks')html=head('Clocks','Visible pressure makes the city feel alive')+`<button id="addClock">+ Add Clock</button><div class="cards topgap">${state.clocks.map(clockHTML).join('')}</div>`;
if(state.page==='npcs')html=head('Faces in the Fog','Give every relationship a voice, desire, and tell')+`<input id="npcSearch" class="search" placeholder="Search name, faction, role…"><div id="npcCards" class="cards">${npcSeeds.map((n,i)=>`<div class="card npc-card" data-npc-card><div class="portrait-sigil">${n.kind.includes('Enemy')?'☠':'♙'}</div><h3>${n.name}</h3><span class="tag ${n.kind.includes('Enemy')?'bad':'good'}">${n.kind}</span>${n.canon?'':'<span class="tag">Campaign seed</span>'}<p><b>${n.role}</b>${n.district!=='—'?' · '+n.district:''}</p><p>${n.details}</p><div class="npc-voice"><b>Voice:</b> ${n.voice}<br><b>Tell:</b> ${n.tell}<br><b>Wants:</b> ${n.want}</div><div class="note"><b>History:</b> ${n.history}</div></div>`).join('')}</div>`;
if(state.page==='gather')html=head('Gather Information','Turn a contact into a lead without stopping play')+`<div class="card contact"><div><h3>Quellyn · Young Witch</h3><span class="tag good">Trusted</span><p>${npcSeeds[0].details}</p><p><b>Her manner:</b> ${npcSeeds[0].voice}</p></div><button id="quellLead">Ask Quellyn for a lead</button></div><div id="lead" class="note hidden"></div><div class="cards topgap"><div class="card"><h3>Quick Questions</h3><p>What is strange here? · What is hidden? · Who benefits? · Who is afraid? · What would make this easier? · What danger is being concealed?</p></div><div class="card"><h3>Information Quality</h3><p>No obstacle: use common knowledge or a fortune roll. Obstacle present: use an action roll and let position/effect follow the fiction.</p></div></div>`;
if(state.page==='score')html=head('Score Engine','Cut to the action; let pressure do the planning')+`<div class="cards"><div class="card"><h3>Plan</h3><select id="planType" class="search"><option>Assault</option><option>Deception</option><option>Stealth</option><option>Occult</option><option>Social</option><option>Transport</option></select><input id="planDetail" class="search" placeholder="Key detail: point, method, entry, power, connection, route…"><button id="rollEngage">Roll engagement</button><div id="engageResult" class="note"></div></div><div class="card"><h3>Score Spark</h3><p id="scoreHook">${pick(scoreHooks)}</p><button id="rerollHook">Draw another</button></div><div class="card"><h3>Heat / Fallout Prompt</h3><p id="fallout">What evidence, witness, debt, injury, or offended faction survives the score?</p><button id="falloutBtn">Generate fallout</button></div></div>`;
if(state.page==='crew')html=head('The Sneaks','Shadows in Doskvol')+`<div class="cards"><div class="card"><h3>Established Threads</h3><p>Quellyn · two clean ingredient thefts<br>Wraiths · faithful Nightmarket tribute<br>Grinders · angered after theft<br>Gray Cloaks · friendly, original reason intentionally left vague</p></div><div class="card"><h3>Identity</h3><p>A Shadows crew survives by preparation, nerve, and getting somewhere they were never meant to be.</p></div></div>`;
if(state.page==='notes')html=head('Session Notes','Catch it before the fog closes over it')+`<div class="card"><textarea id="notes" class="search notes" rows="18" placeholder="People, promises, wounds, rumors, clocks, loot…">${esc(localStorage.getItem('doskvol-notes')||'')}</textarea><p class="small">Saved automatically on this device.</p></div>`;
$('#main').innerHTML=html;wirePage();}
function wirePage(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{state.page=b.dataset.jump;render()});let s=$('#factionSearch');if(s)s.oninput=()=>document.querySelectorAll('[data-faction-card]').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(s.value.toLowerCase())?'':'none');document.querySelectorAll('[data-faction]').forEach(b=>b.onclick=()=>{let f=baseFactions[+b.dataset.faction],cur=state.factionStatus[f.name]??f.status;state.factionStatus[f.name]=Math.max(-3,Math.min(3,cur+Number(b.dataset.delta)));localStorage.setItem('doskvol-faction-status',JSON.stringify(state.factionStatus));render()});let ns=$('#npcSearch');if(ns)ns.oninput=()=>document.querySelectorAll('[data-npc-card]').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(ns.value.toLowerCase())?'':'none');let a=$('#addClock');if(a)a.onclick=()=>{let name=prompt('Clock name?');if(!name)return;let size=Number(prompt('Segments? 4, 6, or 8','6'));if(![4,6,8].includes(size))size=6;state.clocks.push({name,size,filled:0});saveClocks();render()};document.querySelectorAll('[data-clock]').forEach(b=>b.onclick=()=>{let c=state.clocks[+b.dataset.clock],seg=+b.dataset.seg;c.filled=seg<c.filled?seg:seg+1;saveClocks();render()});document.querySelectorAll('[data-delclock]').forEach(b=>b.onclick=()=>{state.clocks.splice(+b.dataset.delclock,1);saveClocks();render()});let q=$('#quellLead');if(q)q.onclick=()=>{let lead=pick(['A spirit keeps repeating the same surname near an abandoned Six Towers house. Quellyn thinks something inside remembers being stolen.','Someone is quietly buying grave-dust, eelglass, and children’s teeth in quantities that make no ritual sense. Quellyn wants to know why.','A collector has an arcane object Quellyn recognizes. She wants it removed intact and does not want the collector harmed.']);$('#lead').classList.remove('hidden');$('#lead').innerHTML='<b>Quellyn says:</b> '+lead};document.querySelectorAll('[data-district]').forEach(b=>b.onclick=()=>{let d=districts[+b.dataset.district];$('#districtInfo').innerHTML=`<h3>${d[0]}</h3><span class="tag">${d[2]} wealth</span><p>${d[1]}</p><div class="note"><b>Score seed:</b> ${pick(scoreHooks)}</div>`});let n=$('#notes');if(n)n.oninput=()=>localStorage.setItem('doskvol-notes',n.value);let nh=$('#newHook');if(nh)nh.onclick=()=>$('#hook').innerHTML='<div class="note">'+pick(scoreHooks)+'</div>';let rh=$('#rerollHook');if(rh)rh.onclick=()=>$('#scoreHook').textContent=pick(scoreHooks);let fb=$('#falloutBtn');if(fb)fb.onclick=()=>$('#fallout').textContent=pick(complications);let re=$('#rollEngage');if(re)re.onclick=()=>{let r=rollPool(1),txt=r.result===6?'Controlled start':r.result>=4?'Risky start':'Desperate start';$('#engageResult').innerHTML=`<b>${txt}</b> · rolled ${r.dice.join(', ')}`};setupOracle();}
function setupOracle(){let pos='risky',eff='standard',pips=1;document.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{pos=b.dataset.pos;document.querySelectorAll('[data-pos]').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('[data-eff]').forEach(b=>b.onclick=()=>{eff=b.dataset.eff;document.querySelectorAll('[data-eff]').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('[data-pips]').forEach(b=>b.onclick=()=>{pips=+b.dataset.pips;document.querySelectorAll('[data-pips]').forEach(x=>x.classList.toggle('selected',x===b))});let r=$('#resolveAction');if(r)r.onclick=()=>{let pool=pips+($('#bonusAssist')?.checked?1:0)+($('#bonusPush')?.checked?1:0),roll=rollPool(pool),i=interpret(pos,eff,roll),dice=roll.dice.join(' · '),zero=roll.zero?' (0d: roll 2, take lower)':'';$('#oracleResult').innerHTML=`<div class="oracle-sigil">${i.cls==='good'?'✦':i.cls==='mixed'?'◐':'☠'}</div><h3 class="${i.cls}">${i.outcome}</h3><div class="rolled">${dice}</div><p><b>${pos.toUpperCase()} · ${eff.toUpperCase()}</b>${zero}</p><p>${i.consequence}</p><div class="note">At ${eff} effect, mark <b>${i.effTicks}</b> segment${i.effTicks>1?'s':''} on an appropriate progress clock.</div>`;localStorage.setItem('doskvol-last-oracle',`${i.outcome} · ${pos} · ${eff} · ${dice}`);let lm=$('#lastOracle');if(lm)lm.textContent=localStorage.getItem('doskvol-last-oracle')||'';}}}
function saveClocks(){localStorage.setItem('doskvol-clocks',JSON.stringify(state.clocks))}
function renderHistory(){$('#rollHistory').textContent=state.rolls.length?'Recent: '+state.rolls.slice(0,6).join(' · '):'No rolls yet.'}
$('#rollDie').onclick=()=>{let d=$('#die');d.classList.remove('rolling');void d.offsetWidth;d.classList.add('rolling');let r=1+Math.floor(Math.random()*6);setTimeout(()=>{d.textContent=r;state.rolls.unshift(r);state.rolls=state.rolls.slice(0,20);localStorage.setItem('doskvol-rolls',JSON.stringify(state.rolls));renderHistory()},260)};$('#rollComplication').onclick=()=>$('#complication').textContent=pick(complications);$('#rollBargain').onclick=()=>$('#bargain').textContent=pick(bargains);document.addEventListener('click',e=>{let j=e.target.closest('[data-jump]');if(j){state.page=j.dataset.jump;render();}});render();renderHistory();$('#lastOracle').textContent=localStorage.getItem('doskvol-last-oracle')||'No action resolved yet.';
