/* Phase 2 — Atmosphere and full Gather Information contact desk. */
(function(){
  const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const scenes={
    street:{name:'Rain on the Narrow Streets',desc:'Cold rain, a distant bell, and the low breath of the city.',mix:{rain:62,steam:26,bell:15,room:12}},
    haunt:{name:'Six Towers Haunt',desc:'A quieter street: damp air, old pipes, and a haunted city keeping its distance.',mix:{rain:32,steam:18,bell:8,room:42}},
    score:{name:'Score Underway',desc:'Tight nerves: rain, pressure, and a far-off alarm bell—not a modern siren.',mix:{rain:38,steam:37,bell:28,room:18}},
    tavern:{name:'The Back Room',desc:'Muted fire, low conversation texture, and rain against the shutters.',mix:{rain:22,steam:8,bell:0,room:65}}
  };
  const stored=JSON.parse(localStorage.getItem('doskval-atmosphere')||'{}');
  let config={scene:stored.scene||'street',playing:false,mix:Object.assign({rain:55,steam:24,bell:14,room:20},stored.mix||{})};
  let ctx=null,nodes=[],timers=[],noise=null;
  function persist(){localStorage.setItem('doskval-atmosphere',JSON.stringify({scene:config.scene,mix:config.mix}));}
  function noiseBuffer(){if(noise)return noise;const b=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return noise=b;}
  function gain(v){const g=ctx.createGain();g.gain.value=v;g.connect(ctx.destination);nodes.push(g);return g;}
  function loopNoise(amount,filterHz,rate=1){const src=ctx.createBufferSource();src.buffer=noiseBuffer();src.loop=true;src.playbackRate.value=rate;const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=filterHz;src.connect(f);f.connect(gain(amount));src.start();nodes.push(src);}
  function bell(){if(!ctx||!config.playing)return;const o=ctx.createOscillator(),g=gain((config.mix.bell||0)/1000),f=ctx.createBiquadFilter();o.type='sine';o.frequency.value=188+Math.random()*14;f.type='lowpass';f.frequency.value=650;o.connect(f);f.connect(g);g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime((config.mix.bell||0)/1000,ctx.currentTime+.03);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+3.2);o.start();o.stop(ctx.currentTime+3.3);}
  function roomTone(){const o=ctx.createOscillator(),g=gain((config.mix.room||0)/1500);o.type='triangle';o.frequency.value=62;o.connect(g);o.start();nodes.push(o);}
  function stop(){config.playing=false;timers.forEach(clearInterval);timers=[];nodes.forEach(n=>{try{n.stop&&n.stop();n.disconnect&&n.disconnect();}catch(_){}});nodes=[];}
  async function start(){stop();ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();await ctx.resume();config.playing=true;loopNoise((config.mix.rain||0)/850,1150,.78);loopNoise((config.mix.steam||0)/1900,340,.42);roomTone();bell();timers.push(setInterval(bell,17000+Math.random()*10000));}
  function setScene(id){config.scene=id;config.mix=Object.assign({},scenes[id].mix);persist();if(config.playing)start();renderCurrent();}
  function controls(){return Object.entries({rain:'Rain',steam:'Steam & machinery',bell:'Distant bells',room:'Interior texture'}).map(([key,label])=>`<div class="mixControl"><label>${label}<output id="out-${key}">${config.mix[key]}%</output></label><input data-mix="${key}" type="range" min="0" max="100" value="${config.mix[key]}"></div>`).join('');}
  function atmospherePage(){return `<div class="pagehead"><div><p>DOSKVAL · TABLE ATMOSPHERE</p><h2>Atmosphere</h2><span>Period-appropriate sound for the city outside the score.</span></div><b>♨ ✦ ♨</b></div><div class="atmoDeck"><section class="panel atmoHero"><h3>THE CITY BREATHES</h3><p>Start a restrained live soundscape from this device. It is built from synthesized rain, steam, bells, and room tone—no modern traffic, sirens, aircraft, or contemporary machinery.</p><div class="atmoState ${config.playing?'playing':''}"><i></i><span>${config.playing?'SOUND RUNNING · tap Stop when the table starts':'SOUND STANDBY · audio begins only after you tap Start'}</span></div><div class="atmoActions"><button id="atmoToggle" class="primary">${config.playing?'STOP ATMOSPHERE':'START ATMOSPHERE'}</button><button id="atmoCue">PLAY A DISTANT BELL</button></div><div class="sceneGrid">${Object.entries(scenes).map(([id,s])=>`<button class="sceneCard ${config.scene===id?'active':''}" data-scene="${id}"><b>${safe(s.name)}</b><small>${safe(s.desc)}</small></button>`).join('')}</div><div class="atmoRule"><b>LOCKED SOUND RULE</b> Old city ambience only. Early motorcars and a rare bulb-horn “honk honk” may be introduced later, but modern engines, traffic beds, sirens, and airplanes stay out.</div></section><aside class="atmoMix"><section class="panel"><header><span>⚙</span><h2>MIX DESK</h2></header>${controls()}</section><section class="panel atmoCue"><h3>GM CUE</h3><p class="cueText" id="atmoCueText">${safe(scenes[config.scene].desc)}</p><p class="hint">Sound stays local to this dashboard and never starts on its own.</p></section></aside></div>`;}
  function contactData(){return window.DOSKVAL_LORE?.contacts||[];}
  function gatherPage(){const contacts=contactData();return `<div class="pagehead"><div><p>DOSKVAL · INFORMATION NETWORK</p><h2>Gather Information</h2><span>Choose the person who can actually move the investigation forward.</span></div><b>◉ ✦ ◉</b></div><section class="panel atmoContactIntro"><h3>THE SNEAKS’ CONTACTS</h3><p>All character and Shadows crew contacts are here—not just Quellyn. Tap one to set the kind of information they can provide, then choose the quality of the result.</p><div class="contactFilter"><button class="active" data-contact-filter="all">ALL CONTACTS · ${contacts.length}</button><button data-contact-filter="friend">FRIENDS</button><button data-contact-filter="rival">RIVALS</button><button data-contact-filter="crew">CREW CONTACTS</button></div><div class="gatherContactGrid" id="gatherContactGrid">${contacts.map(c=>`<button class="gatherContact" data-contact="${safe(c.name)}" data-kind="${/crew/i.test(c.group)?'crew':c.status.toLowerCase()}"><span class="contactTag">${safe(c.group)}</span><span class="status">${safe(c.status)}</span><h3>${safe(c.name)}</h3><b>${safe(c.role)}</b><p>${safe(c.sentence)}</p></button>`).join('')}</div></section><section class="panel gatherDetail" id="gatherDetail" hidden></section><section class="panel"><h3>QUESTIONS THAT MOVE PLAY</h3><p>What is really going on here? · What should I be worried about? · Where is the weakness? · Who benefits if this goes wrong? · What opportunity is everyone overlooking?</p></section>`;}
  function gatherResult(name,quality){const d={limited:'The lead is true, but the crucial detail needs another source.',standard:'They provide a usable lead and a clear next step.',great:'They expose hidden leverage as well as the lead.'}[quality];return `<b>${quality.toUpperCase()} INFORMATION</b><p><strong>${safe(name)}</strong> says: ${safe(d)}</p><p class="hint">Use the NPC / Faces panel for that contact’s detailed activity, rumours, and generated dossier.</p>`;}
  function bindGather(){
    const grid=document.getElementById('gatherContactGrid');if(!grid)return;const contacts=contactData();
    document.querySelectorAll('[data-contact-filter]').forEach(b=>b.onclick=()=>{
      document.querySelectorAll('[data-contact-filter]').forEach(x=>x.classList.toggle('active',x===b));
      const f=b.dataset.contactFilter;
      grid.querySelectorAll('.gatherContact').forEach(c=>{c.hidden=!(f==='all'||c.dataset.kind===f);});
    });
    grid.querySelectorAll('.gatherContact').forEach(b=>b.onclick=()=>{
      const c=contacts.find(x=>x.name===b.dataset.contact),d=document.getElementById('gatherDetail');d.hidden=false;
      d.innerHTML=`<h3>ASK ${safe(c.name.toUpperCase())}</h3><p><b>${safe(c.role)}</b> · ${safe(c.group)}</p><p>${safe(c.sentence)}</p><fieldset><legend>RESULT QUALITY</legend><label><input type="radio" name="gq" value="limited"> Limited</label><label><input type="radio" name="gq" value="standard" checked> Standard</label><label><input type="radio" name="gq" value="great"> Great</label></fieldset><button id="askContact" class="primary">GATHER INFORMATION</button><div id="gatherAnswer" class="intelResult"><span>Choose a result quality and ask the question.</span></div>`;
      d.querySelector('#askContact').onclick=()=>d.querySelector('#gatherAnswer').innerHTML=gatherResult(c.name,d.querySelector('input[name="gq"]:checked').value);
      d.scrollIntoView({behavior:'smooth',block:'nearest'});
    });
  }
  function bindAtmo(){document.getElementById('atmoToggle')?.addEventListener('click',async()=>{if(config.playing)stop();else await start();renderCurrent();});document.getElementById('atmoCue')?.addEventListener('click',bell);document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>setScene(b.dataset.scene));document.querySelectorAll('[data-mix]').forEach(i=>i.oninput=()=>{config.mix[i.dataset.mix]=+i.value;document.getElementById('out-'+i.dataset.mix).textContent=i.value+'%';persist();if(config.playing)start();});}
  const baseRender=window.render; function renderCurrent(){baseRender();if(state.page==='atmosphere'){$('#main').innerHTML=atmospherePage();bindAtmo();}if(state.page==='gather'){$('#main').innerHTML=gatherPage();bindGather();}}
  if(!nav.some(x=>x[0]==='atmosphere'))nav.splice(nav.findIndex(x=>x[0]==='gather'),0,['atmosphere','♨','Atmosphere','Set the Mood']);
  window.render=renderCurrent;renderCurrent();
  window.addEventListener('beforeunload',stop);
})();
