window.DOSKVOL_DATA = {
  sources: {
    core: {label:'Core Book', detail:'Blades in the Dark v8.2'},
    deep: {label:'Deep Cuts', detail:'Expanded faction/lore layer'},
    campaign: {label:'Campaign', detail:'The Sneaks — table canon; overrides published material'}
  },
  factions: [
    {name:'The Unseen',tier:4,hold:'strong',category:'Underworld',source:'deep'},
    {name:'The Hive',tier:4,hold:'strong',category:'Underworld',source:'core+deep'},
    {name:'The Circle of Flame',tier:3,hold:'strong',category:'Underworld',source:'core+deep'},
    {name:'The Silver Nails',tier:3,hold:'strong',category:'Underworld',source:'core+deep'},
    {name:'Lord Scurlock',tier:3,hold:'strong',category:'Underworld',source:'core+deep'},
    {name:'The Crows',tier:2,hold:'weak',category:'Underworld',source:'core+deep',situation:'Roric is dead; Lyssa leads while Crow’s Foot destabilizes.',tags:['leadership crisis','Crow’s Foot']},
    {name:'The Lampblacks',tier:2,hold:'weak',category:'Underworld',source:'core+deep',tags:['Crow’s Foot']},
    {name:'The Red Sashes',tier:2,hold:'weak',category:'Underworld',source:'core+deep',tags:['Crow’s Foot']},
    {name:'The Dimmer Sisters',tier:2,hold:'strong',category:'Underworld',source:'core+deep'},
    {name:'Imperial Military',tier:6,hold:'strong',category:'Institutions',source:'deep',situation:'The Imperium is expanding military capacity and conscription in advance of a mysterious future war.'},
    {name:'Covenant',tier:6,hold:'strong',category:'Institutions',source:'deep'},
    {name:'City Council',tier:5,hold:'strong',category:'Institutions',source:'core+deep'},
    {name:'Ministry of Preservation',tier:5,hold:'strong',category:'Institutions',source:'core+deep'},
    {name:'Unity Commission',tier:5,hold:'strong',category:'Institutions',source:'deep'},
    {name:'Ironhook Prison',tier:4,hold:'strong',category:'Institutions',source:'core+deep'},
    {name:'Rowan House',tier:4,hold:'strong',category:'Institutions',source:'deep'},
    {name:'Sparkwrights',tier:4,hold:'strong',category:'Institutions',source:'core+deep'},
    {name:'The Foundation',tier:4,hold:'strong',category:'Labor & Trade',source:'deep'},
    {name:'Dockers',tier:3,hold:'strong',category:'Labor & Trade',source:'core+deep'},
    {name:'Gondoliers',tier:3,hold:'strong',category:'Labor & Trade',source:'core+deep'},
    {name:'Sailors',tier:3,hold:'weak',category:'Labor & Trade',source:'deep',situation:'Sailors are resisting forced conscription into the growing Imperial war fleet.'},
    {name:'Laborers',tier:3,hold:'strong',category:'Labor & Trade',source:'deep'},
    {name:'Cabbies',tier:2,hold:'strong',category:'Labor & Trade',source:'deep'},
    {name:'Cyphers',tier:2,hold:'strong',category:'Labor & Trade',source:'deep'},
    {name:'Ink Rakes',tier:2,hold:'weak',category:'Labor & Trade',source:'deep'},
    {name:'Ironworks Labor',tier:2,hold:'strong',category:'Labor & Trade',source:'deep',situation:'Coalridge and Charhollow laborers are organizing against brutal conditions and union busting.'},
    {name:'The Church of Ecstasy',tier:4,hold:'strong',category:'The Fringe',source:'core+deep'},
    {name:'The Horde',tier:3,hold:'strong',category:'The Fringe',source:'deep'},
    {name:'The Path of Echoes',tier:3,hold:'strong',category:'The Fringe',source:'deep',situation:'The cult seeks control of the Archive of Echoes before it can be removed from Doskvol.'},
    {name:'The Forgotten Gods',tier:3,hold:'weak',category:'The Fringe',source:'core+deep'},
    {name:'The Reconciled',tier:3,hold:'strong',category:'The Fringe',source:'core+deep'},
    {name:'Skovlander Refugees',tier:3,hold:'strong',category:'The Fringe',source:'core+deep'},
    {name:'Deathlands Scavengers',tier:2,hold:'weak',category:'The Fringe',source:'core+deep'},
    {name:'Ragskulla',tier:2,hold:'strong',category:'The Fringe',source:'deep'},
    {name:'The Weeping Lady',tier:2,hold:'strong',category:'The Fringe',source:'deep'},
    {name:'Bluecoats',tier:3,hold:'strong',category:'Core Book — Other',source:'core'},
    {name:'The Billhooks',tier:2,hold:'strong',category:'Core Book — Other',source:'core'},
    {name:'The Brigade',tier:2,hold:'strong',category:'Core Book — Other',source:'core'},
    {name:'The Fog Hounds',tier:1,hold:'weak',category:'Core Book — Other',source:'core'},
    {name:'The Grinders',tier:2,hold:'weak',category:'Core Book — Other',source:'core'},
    {name:'The Inspectors',tier:3,hold:'strong',category:'Core Book — Other',source:'core'},
    {name:'Rail Jacks',tier:2,hold:'strong',category:'Core Book — Other',source:'core'},
    {name:'Spirit Wardens',tier:4,hold:'strong',category:'Core Book — Other',source:'core'},
    {name:'Ulf Ironborn',tier:1,hold:'strong',category:'Core Book — Other',source:'core'},
    {name:'The Wraiths',tier:2,hold:'weak',category:'Core Book — Other',source:'core'},
    {name:'The Gray Cloaks',tier:2,hold:'weak',category:'Core Book — Other',source:'core'}
  ],
  crew: {
    name:'The Sneaks',icon:'hood',type:'Shadows',source:'campaign',
    summary:'A stealth-focused crew whose table history overrides published starting assumptions.',
    contacts:[{name:'Quellyn',role:'Young witch',district:'Six Towers',relationship:'Trusted',details:'Lives in a cottage behind a low stone fence. Her garden is mostly fungi and Doskvol-suited growth, sustained in part by genuine magic; drying herbs hang inside.'}]
  },
  campaignRelations: [
    {a:'The Sneaks',b:'The Gray Cloaks',v:2,source:'campaign',why:'The Gray Cloaks favor The Sneaks for a reason established during crew creation. The exact reason is intentionally left unknown rather than invented.'},
    {a:'The Sneaks',b:'The Wraiths',v:1,source:'campaign',why:'The Wraiths use Nightmarket as a hunting ground, and The Sneaks have faithfully paid them tribute.'},
    {a:'The Sneaks',b:'The Grinders',v:-2,source:'campaign',why:'The Sneaks stole from the Grinders; the Grinders are angry and remain an active pressure.'}
  ],
  canonRelations: [
    {a:'The Crows',b:'The Lampblacks',v:-1,source:'core',why:'Roric’s death destabilizes Crow’s Foot and the Lampblacks press into the power vacuum.'},
    {a:'The Crows',b:'The Red Sashes',v:-1,source:'core',why:'Roric’s death destabilizes Crow’s Foot and the Red Sashes press into the power vacuum.'},
    {a:'The Lampblacks',b:'The Red Sashes',v:-3,source:'core',why:'They begin in open gang war over Crow’s Foot.'},
    {a:'Sailors',b:'Imperial Military',v:-2,source:'deep',why:'Forced military conscription puts the Sailors in direct conflict with Imperial forces.'},
    {a:'The Path of Echoes',b:'The Church of Ecstasy',v:-1,source:'deep',why:'Deep Cuts lists the Church among the Path of Echoes’ enemies.'},
    {a:'The Path of Echoes',b:'The Dimmer Sisters',v:-1,source:'deep',why:'Deep Cuts lists the Dimmer Sisters among the Path of Echoes’ enemies.'},
    {a:'The Path of Echoes',b:'The Reconciled',v:1,source:'deep',why:'Deep Cuts lists the Reconciled among the Path of Echoes’ allies.'},
    {a:'The Path of Echoes',b:'The Red Sashes',v:1,source:'deep',why:'Deep Cuts lists the Red Sashes among the Path of Echoes’ allies.'},
    {a:'Sailors',b:'The Crows',v:1,source:'deep',why:'Deep Cuts lists the Crows among the Sailors’ allies.'},
    {a:'Sailors',b:'Dockers',v:1,source:'deep',why:'Deep Cuts lists the Dockers among the Sailors’ allies.'},
    {a:'Sailors',b:'The Silver Nails',v:1,source:'deep',why:'Deep Cuts lists the Silver Nails among the Sailors’ allies.'},
    {a:'Ironworks Labor',b:'Bluecoats',v:-2,source:'deep',why:'Bluecoat union-busting puts them directly against organized labor.'},
    {a:'Ironworks Labor',b:'City Council',v:-2,source:'deep',why:'The Council opposes the labor movement and its demands.'},
    {a:'Ironworks Labor',b:'The Lampblacks',v:1,source:'deep',why:'Deep Cuts lists the Lampblacks among Ironworks Labor’s allies.'},
    {a:'Imperial Military',b:'The Silver Nails',v:1,source:'deep',why:'Deep Cuts lists the Silver Nails among Imperial Military allies.'},
    {a:'Imperial Military',b:'Ministry of Preservation',v:1,source:'deep',why:'Deep Cuts lists the Ministry among Imperial Military allies.'},
    {a:'Imperial Military',b:'Bluecoats',v:-1,source:'deep',why:'Deep Cuts lists the Bluecoats among Imperial Military enemies.'}
  ],
  districts:['Whitecrown','Brightstone','Charterhall','Six Towers','Silkshore','Nightmarket','Crow’s Foot','The Docks','Barrowcleft','Coalridge','Charhollow','Dunslough'],
  loreLayers:[
    {id:'core',title:'Core Canon',rule:'The main rulebook is the baseline for Doskvol, its districts, institutions, factions, and starting situation.'},
    {id:'deep',title:'Deep Cuts',rule:'Expanded lore, 27 full faction treatments, setting innovations, and catalysts sit on top of the core setting. Alternate mechanics are not enabled by default.'},
    {id:'campaign',title:'Campaign Canon',rule:'Anything established at your table overrides published assumptions for this campaign.'}
  ]
};
