// Doskval Dashboard · The Sneaks Crew HQ
// Mirrors the core Shadows crew sheet while adding persistent campaign tracking.
(()=>{
const KEY='doskvalCrewHQv1';
const base={tier:0,hold:'Strong',rep:0,heat:0,wanted:0,coin:2,xp:0,reputation:'',lair:'',huntingDistrict:'Nightmarket',favoredOperation:'',upgrades:{'Training: Prowess':true,'Hidden Lair':true},abilities:[],claims:[],cohorts:[]};
let s={...base,...JSON.parse(localStorage.getItem(KEY)||'{}')}; s.upgrades={...base.upgrades,...(s.upgrades||{})};
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
const upgrades=[['Thief Rigging',1],['Underground Maps and Passkeys',1],['Elite Rooks',1],['Elite Skulks',1],['Steady',3],['Boat House',2],['Carriage House',2],['Cohort',2],['Hidden Lair',1],['Mastery',4],['Quality: Documents',1],['Quality: Gear',1],['Quality: Arcane Implements',1],['Quality: Subterfuge Supplies',1],['Quality: Tools',1],['Quality: Weapons',1],['Quarters',1],['Secure Lair',2],['Training: Insight',1],['Training: Prowess',1],['Training: Resolve',1],['Training: Playbook',1],['Vault',2],['Workshop',1]];
const abilities=['Everyone Steals','Ghost Echoes','Pack Rats','Patron','Second Story','Slippery','Synchronized'];
const claims=['Interrogation Chamber','Turf A','Loyal Fence','Gambling Den','Tavern','Drug Den','Informants','Lair','Turf B','Lookouts','Hagfish Farm','Infirmary','Covert Drop','Turf C','Secret Pathways'];
const claimInfo={'Interrogation Chamber':'+1d to Command and Sway on-site.','Drug Den':'Downtime income: roll Tier; earn highest result minus Heat.','Gambling Den':'Downtime income: roll Tier; earn highest result minus Heat.','Hagfish Farm':'+1d to reduce Heat after a score involving killing.','Infirmary':'+1d to healing treatment rolls.','Informants':'+1d to gather information for a score.','Lookouts':'+1d to Hunt or Survey on your turf.','Loyal Fence':'+2 coin payoff for burglary or robbery scores.','Covert Drop':'+2 coin payoff for espionage or sabotage scores.','Secret Pathways':'+1d engagement for stealth plans.','Tavern':'+1d to Consort and Sway on-site.','Turf A':'Expands hunting grounds and helps crew development.','Turf B':'Expands hunting grounds and helps crew development.','Turf C':'Expands hunting grounds and helps crew development.','Lair':'The centre of the Sneaks’ claim network.'};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function dots(name,val,max){return `<div class="crewDots" data-dotset="${name}">${Array.from({length:max},(_,i)=>`<button data-dot="${i+1}" class="${i<val?'on':''}"></button>`).join('')}</div>`}
function upgradeRow([n,c]){let v=s.upgrades[n]||false, marks=typeof v==='number'?v:(v?c:0);return `<button class="crewUpgrade ${marks>=c?'owned':''}" data-upgrade="${esc(n)}" data-cost="${c}"><span>${esc(n)}</span><i>${Array.from({length:c},(_,i)=>i<marks?'●':'○').join('')}</i></button>`}
function render(){
 const main=document.querySelector('#main'); if(!main)return;
 main.innerHTML=`<div class="crewHQ"><div class="crewHQTop"><div><div class="eyebrow">SHADOWS CREW · THIEVES & SPIES</div><h1>THE SNEAKS</h1><p>Quiet doors. Loud consequences.</p></div><button class="crewBack">← HOME</button></div>
 <div class="crewTabs"><button class="active" data-ctab="status">CREW SHEET</button><button data-ctab="growth">UPGRADES & ASSETS</button><button data-ctab="turf">TURF & CLAIMS</button></div>
 <section class="crewPane active" data-pane="status"><div class="crewStatGrid">
 <article><h3>CREW STATUS</h3><label>Tier <input type="number" min="0" max="6" data-field="tier" value="${s.tier}"></label><label>Hold <select data-field="hold"><option ${s.hold==='Strong'?'selected':''}>Strong</option><option ${s.hold==='Weak'?'selected':''}>Weak</option></select></label><label>Reputation <input data-field="reputation" value="${esc(s.reputation)}" placeholder="Subtle, Daring, Strange…"></label><label>Crew XP ${dots('xp',s.xp,10)}</label></article>
 <article><h3>HEAT & WANTED</h3><label>Heat ${dots('heat',s.heat,9)}</label><label>Wanted Level ${dots('wanted',s.wanted,4)}</label><label>Rep ${dots('rep',s.rep,12)}</label></article>
 <article><h3>COIN / VAULT</h3><div class="coinRead"><b>${s.coin}</b><span>/ ${s.upgrades['Vault']===2?16:s.upgrades['Vault']?8:4} coin capacity</span></div><input type="range" min="0" max="${s.upgrades['Vault']===2?16:s.upgrades['Vault']?8:4}" value="${s.coin}" data-field="coin"><small>Vault I expands storage to 8; Vault II to 16.</small></article>
 <article><h3>HUNTING GROUNDS</h3><label>District <input data-field="huntingDistrict" value="${esc(s.huntingDistrict)}"></label><label>Favored operation <select data-field="favoredOperation"><option></option>${['Burglary','Espionage','Robbery','Sabotage'].map(x=>`<option ${s.favoredOperation===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Lair <input data-field="lair" value="${esc(s.lair)}" placeholder="Describe the lair…"></label><button class="exploreTurf">EXPLORE OUR TURF</button></article></div>
 <article class="crewWide"><h3>SPECIAL ABILITIES</h3><div class="abilityGrid">${abilities.map(a=>`<button class="ability ${s.abilities.includes(a)?'owned':''}" data-ability="${a}">${s.abilities.includes(a)?'◆':'◇'} ${a}</button>`).join('')}</div></article></section>
 <section class="crewPane" data-pane="growth"><article class="crewWide"><h3>SHADOWS + GENERAL CREW UPGRADES</h3><p class="crewHint">Tap boxes as the Sneaks advance. Starting Shadows upgrades are Prowess Training and Hidden Lair.</p><div class="upgradeGrid">${upgrades.map(upgradeRow).join('')}</div></article><article class="crewWide"><h3>COHORTS · GANGS & EXPERTS</h3><div id="cohortList">${s.cohorts.map((c,i)=>`<div class="cohort"><b>${esc(c.name)}</b><span>${esc(c.type)} · ${esc(c.kind)}</span><button data-delcohort="${i}">×</button></div>`).join('')||'<p class="crewHint">No cohorts recorded yet.</p>'}</div><div class="cohortAdd"><input id="coName" placeholder="Name"><select id="coKind"><option>Gang</option><option>Expert</option></select><input id="coType" placeholder="Type: Skulks, Rooks, Spy…"><button id="addCohort">ADD COHORT</button></div></article></section>
 <section class="crewPane" data-pane="turf"><article class="crewWide"><h3>SHADOWS CLAIM MAP</h3><p class="crewHint">The roadmap mirrors the Shadows crew sheet. Tap a claim when the Sneaks seize it.</p><div class="claimMap">${claims.map(c=>`<button class="claim ${c==='Lair'?'lair':''} ${s.claims.includes(c)?'owned':''}" data-claim="${c}" title="${esc(claimInfo[c])}"><b>${c}</b><small>${esc(claimInfo[c])}</small></button>`).join('')}</div></article><article class="crewWide turfTools"><h3>OUR TURF</h3><p><b>Current hunting ground:</b> ${esc(s.huntingDistrict||'Not set')}</p><p>The crew knows its hunting ground especially well. As Turf is acquired, expand the territory and/or operation types represented here.</p><button class="openMap">OPEN DOSKVAL MAP</button></article></section></div>`;
 bind();
}
function bind(){
 document.querySelector('.crewBack')?.addEventListener('click',()=>{ if(window.setPage)window.setPage('home'); else location.reload(); });
 document.querySelectorAll('[data-ctab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-ctab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-pane]').forEach(p=>p.classList.toggle('active',p.dataset.pane===b.dataset.ctab));});
 document.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{let k=el.dataset.field;s[k]=el.type==='number'||el.type==='range'?+el.value:el.value;save();if(k==='coin')el.closest('article').querySelector('.coinRead b').textContent=s.coin;});
 document.querySelectorAll('[data-dotset]').forEach(set=>set.querySelectorAll('[data-dot]').forEach(b=>b.onclick=()=>{let k=set.dataset.dotset,v=+b.dataset.dot;s[k]=s[k]===v?0:v;save();set.querySelectorAll('button').forEach(x=>x.classList.toggle('on',+x.dataset.dot<=s[k]));}));
 document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{let n=b.dataset.upgrade,c=+b.dataset.cost,cur=s.upgrades[n]||0;cur=typeof cur==='boolean'?(cur?c:0):cur;s.upgrades[n]=(cur+1)%(c+1);save();render();document.querySelector('[data-ctab="growth"]')?.click();});
 document.querySelectorAll('[data-ability]').forEach(b=>b.onclick=()=>{let a=b.dataset.ability;s.abilities=s.abilities.includes(a)?s.abilities.filter(x=>x!==a):[...s.abilities,a];save();b.classList.toggle('owned');b.textContent=(s.abilities.includes(a)?'◆ ':'◇ ')+a;});
 document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{let c=b.dataset.claim;if(c==='Lair')return;s.claims=s.claims.includes(c)?s.claims.filter(x=>x!==c):[...s.claims,c];save();b.classList.toggle('owned');});
 document.querySelector('#addCohort')?.addEventListener('click',()=>{let name=document.querySelector('#coName').value.trim(),kind=document.querySelector('#coKind').value,type=document.querySelector('#coType').value.trim();if(!name)return;s.cohorts.push({name,kind,type});save();render();document.querySelector('[data-ctab="growth"]')?.click();});
 document.querySelectorAll('[data-delcohort]').forEach(b=>b.onclick=()=>{s.cohorts.splice(+b.dataset.delcohort,1);save();render();document.querySelector('[data-ctab="growth"]')?.click();});
 document.querySelector('.openMap')?.addEventListener('click',()=>window.setPage&&window.setPage('map'));
 document.querySelector('.exploreTurf')?.addEventListener('click',()=>{document.querySelector('[data-ctab="turf"]')?.click();});
}
function intercept(){
 document.addEventListener('click',e=>{let b=e.target.closest('[data-page="crew"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();setTimeout(render,0);},true);
}
intercept();
})();