const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], pick=a=>a[Math.floor(Math.random()*a.length)], esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nav=[['home','⌂','Home','At a Glance'],['oracle','⚄','Action Oracle','Resolve an Action'],['score','⚔','Scores','Plan the Job'],['factions','♟','Factions','Faction Ledger'],['web','⌘','Faction Web','Who vs Who'],['map','⌖','Map','Explore Doskval'],['clocks','◷','Clocks','Track Progress'],['faces','☻','NPCs / Faces','People & Rumours'],['gather','◉','Gather Info','Find the Truth'],['notes','▤','Session Notes','Remember It'],['advance','⌛','Advance Time','Let the City Move'],['settings','⚙','Settings','Your Table']];
const factions=[
{name:'The Crows',tier:'II',hold:'Weak',canon:'Crow’s Foot leadership is unstable after Roric’s death and Lyssa’s rise.',crew:0,icon:'◉'},
{name:'The Lampblacks',tier:'II',hold:'Weak',canon:'A major Crow’s Foot gang locked in conflict with the Red Sashes.',crew:0,icon:'♜'},
{name:'The Red Sashes',tier:'II',hold:'Weak',canon:'A major Crow’s Foot gang locked in conflict with the Lampblacks.',crew:0,icon:'⚔'},
{name:'The Wraiths',tier:'II',hold:'Weak',canon:'A crew of mysterious thieves and spies.',crew:1,icon:'☠',campaign:'The Sneaks faithfully pay tribute for their Nightmarket hunting ground.'},
{name:'Gray Cloaks',tier:'II',hold:'Strong',canon:'Former Bluecoats turned criminals.',crew:2,icon:'▣',campaign:'They favor The Sneaks; the exact chargen reason remains intentionally unknown.'},
{name:'The Grinders',tier:'II',hold:'Weak',canon:'Skovlander radicals and toughs.',crew:-2,icon:'⚙',campaign:'Angered because The Sneaks stole from them.'},
{name:'The Dimmer Sisters',tier:'II',hold:'Strong',canon:'An occult household with deep supernatural interests.',crew:0,icon:'☾'},
{name:'The Hive',tier:'IV',hold:'Strong',canon:'Powerful mercantile criminal interests.',crew:0,icon:'⬡'},
{name:'The Silver Nails',tier:'III',hold:'Strong',canon:'Mercenaries and ghost-fighters.',crew:0,icon:'✦'},
{name:'Bluecoats',tier:'III',hold:'Strong',canon:'Doskvol’s city watch.',crew:0,icon:'⬙'},
{name:'Inspectors',tier:'III',hold:'Strong',canon:'Investigators pursuing major crimes and corruption.',crew:0,icon:'◉'},
{name:'Spirit Wardens',tier:'IV',hold:'Strong',canon:'Elite occult authorities who respond to deaths and spirits.',crew:0,icon:'♨'},
{name:'Church of Ecstasy',tier:'IV',hold:'Strong',canon:'A powerful state religion concerned with transcendence beyond the body.',crew:0,icon:'☼'},
{name:'Billhooks',tier:'II',hold:'Strong',canon:'A brutal criminal gang with family ties and bloody methods.',crew:0,icon:'Ψ'},
{name:'Gondoliers',tier:'III',hold:'Strong',canon:'Canal boatmen with deep knowledge of the waterways and supernatural trouble.',crew:0,icon:'≈'}
];
const baselineRels={
'The Lampblacks|The Red Sashes':{status:'war',why:'Canon starting conflict in Crow’s Foot.'},
'The Crows|The Lampblacks':{status:'rival',why:'Crow’s Foot power struggle after Roric’s death.'},
'The Crows|The Red Sashes':{status:'rival',why:'Crow’s Foot power struggle after Roric’s death.'}
};
const districts=[['Whitecrown','Imperial power, institutions, estates.'],['Brightstone','Old money, luxury and polished danger.'],['Charterhall','Civic offices, commerce and respectable corruption.'],['Six Towers','Faded nobility, haunted estates and Quellyn’s cottage.'],['Silkshore','Pleasure, art, vice and spectacle.'],['Nightmarket','Rail trade, rare goods and illicit commerce.'],["Crow’s Foot",'Gang turf, stacked streets and volatile borders.'],['The Docks','Warehouses, sailors, taverns and violence.'],['Barrowcleft','Markets, food production and working families.'],['Coalridge','Factories, soot, labour and old industry.'],['Charhollow','Crowded tenements and hard lives.'],['Dunslough','Poverty, prison labour and desperation.']];
const faces=[
{name:'Quellyn',role:'Young witch · Six Towers',kind:'Campaign canon',voice:'Curious, quick and quietly intense; distracted by odd details until she snaps back with unnerving precision.',tell:'Sorts herbs, bones or chalk while talking.',want:'Rare ingredients, occult answers and calm people around the supernatural.',history:'The Sneaks completed two ingredient thefts for her with no Heat.',details:'Cottage behind a low stone fence. A mostly fungal garden survives Doskval with a little real magic; herbs dry from the ceiling.'},
{name:'Lyssa',role:'Boss of the Crows',kind:'Published canon',voice:'Use the book’s established characterization as baseline; let play define the voice at your table.',tell:'Power is recent and contested.',want:'Hold the Crows together and survive the Crow’s Foot struggle.',history:'Rose after Roric’s death.'},
{name:'Roric',role:'Former boss of the Crows',kind:'Published canon',voice:'Dead, but his shadow remains politically useful.',tell:'People still invoke his name.',want:'—',history:'His death destabilized Crow’s Foot.'},
{name:'Ragged Tom',role:'Lampblack face',kind:'GM seed',voice:'Charismatic, soot-stained, laughs before he threatens.',tell:'Rolls a spent match between his fingers.',want:'A decisive edge over the Red Sashes.',history:'Replace freely when play establishes a stronger face.'},
{name:'Iruvian Dusk',role:'Wraith intermediary',kind:'GM seed',voice:'Low voice, precise words, never repeats a warning.',tell:'Never turns his back on a doorway.',want:'Tribute paid and Nightmarket arrangements respected.',history:'Campaign-facing personality seed.'}
];
const scoreHooks=['A rail cargo changes hands for three minutes in Nightmarket.','A ruined Six Towers manor has one lit window.','A Bluecoat evidence wagon follows a repeating route.','A Grinder courier carries something worth more than his life.','An occult collector wants an object stolen intact and refuses to say why.','A locked-room theft during a funeral wake.'];
const complications=['Unwanted attention arrives now.','The position worsens.','Evidence points toward the crew.','Someone important is put at risk.','A useful resource is lost or damaged.','A faction notices and takes an interest.','The escape route closes.','A danger clock advances.','Reduced effect: they get less than they hoped for.'];
const bargains=['A rival faction learns what you are attempting.','Someone innocent will be caught in the consequences.','Tick a danger clock now.','You owe an inconvenient favor.','A contact is endangered by helping.','The supernatural notices you.','Your presence becomes known regardless of the roll.'];
const defaults={page:'home',clocks:[{name:'Grinders retaliate',size:6,filled:2},{name:'Wraith suspicion',size:4,filled:0},{name:'Bluecoat investigation',size:6,filled:1}],notes:'',next:['Follow up with Quellyn.','Resolve Nightmarket business.','Advance faction clocks.','Update faction reactions.','Prep one strong opportunity.'],checked:{},rels:{},factionStatus:{},developments:['Roric’s death leaves the Crows under Lyssa in an unstable position.','Lampblacks and Red Sashes remain at war.','The Sneaks continue paying Wraith tribute for Nightmarket access.','Gray Cloaks remain favorable toward The Sneaks.'],day:0};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem('doskval-v3')||'{}'));
function save(){localStorage.setItem('doskval-v3',JSON.stringify(state));}
function setPage(p){state.page=p;save();render();window.scrollTo({top:0,behavior:'smooth'});}
function navHTML(){return `<div class="nav-title">THE BLACK LEDGER</div>${nav.map(([id,ic,t,sub])=>`<button class="navbtn ${state.page===id?'active':''}" data-page="${id}"><span class="navicon">${ic}</span><span><b>${t}</b><small>${sub}</small></span></button>`).join('')}<div class="nav-quote">Same city.<br><em>Different story.</em></div>`}
const hood=`<svg class="hood-svg" viewBox="0 0 160 160" aria-label="hooded figure"><defs><radialGradient id="g"><stop offset="0" stop-color="#8af7df" stop-opacity=".18"/><stop offset="1" stop-color="#061012" stop-opacity="0"/></radialGradient></defs><circle cx="80" cy="80" r="76" fill="url(#g)"/><path d="M80 18c-33 8-50 43-46 75l-18 51h128l-18-51c4-32-13-67-46-75z" fill="#0a1418" stroke="#5cbcae" stroke-width="2"/><path d="M47 82c7-34 26-47 33-50 8 3 27 16 34 50-9-11-20-17-34-18-14 1-25 7-33 18z" fill="#173039"/><path d="M57 89c7-10 14-15 23-16 9 1 16 6 23 16-5 30-13 42-23 42s-18-12-23-42z" fill="#020506"/><path d="M66 93l10 3m8 0l10-3" stroke="#88f1dc" stroke-width="3" stroke-linecap="round" opacity=".75"/></svg>`;
function clockMini(c,i){return `<div class="clockline"><button class="clockdisc" data-clockjump="${i}" style="--p:${c.filled/c.size*360}deg"><i></i></button><div><b>${esc(c.name)}</b><small>${c.filled} / ${c.size}</small></div></div>`}
function relationKey(a,b){return [a,b].sort().join('|')}
function getRel(a,b){return state.rels[relationKey(a,b)]||baselineRels[relationKey(a,b)]||{status:'unknown',why:'No starting relationship established here.'}}
function webGraphic(full=false){const nodes=(full?factions.slice(0,12):factions.slice(0,8)); const positions=nodes.map((_,i)=>{const a=(Math.PI*2*i/nodes.length)-Math.PI/2;return {x:50+40*Math.cos(a),y:50+40*Math.sin(a)}});return `<div class="webstage">${nodes.map((f,i)=>{let r=getRel('The Sneaks',f.name);let crew=state.factionStatus[f.name]??f.crew;let cls=crew>0?'friendly':crew<0?'hostile':'unknown';return `<button class="webnode ${cls}" style="left:${positions[i].x}%;top:${positions[i].y}%" data-focusf="${esc(f.name)}"><span>${f.icon}</span><b>${f.name}</b></button>`}).join('')}<button class="webcenter" data-page="crew">${hood}<b>THE SNEAKS</b></button><svg class="weblines" viewBox="0 0 100 100" preserveAspectRatio="none">${positions.map((p,i)=>{let f=nodes[i],v=state.factionStatus[f.name]??f.crew,cls=v>0?'friend':v<0?'enemy':'neutral';return `<line class="${cls}" x1="50" y1="50" x2="${p.x}" y2="${p.y}"/>`}).join('')}</svg></div>`}
function panel(title,icon,body,extra=''){return `<section class="panel"><header><span>${icon}</span><h2>${title}</h2>${extra}</header>${body}</section>`}
function home(){return `<div class="dashboard-grid">
${panel('The Sneaks','◈',`<div class="crewhero">${hood}<div><h3>THE SNEAKS</h3><p class="subtitle">Shadows Crew · Quiet doors. Loud consequences.</p><div class="stats"><span>Playbook <b>Shadows</b></span><span>Heat <b>●●○○○○</b></span><span>Coin <b>●●●●○○</b></span><span>Reputation <b>◆◆◇◇</b></span></div><button data-page="crew">Crew Details</button></div></div>`,'<button data-page="crew">DETAILS</button>')}
${panel('Recent Developments','◉',`<div class="developments">${state.developments.slice(0,5).map((d,i)=>`<div><span class="devicon">${['◉','⚔','☠','⬙','?'][i]||'•'}</span><p>${esc(d)}</p></div>`).join('')}</div>`,'<button data-page="advance">CITY PULSE</button>')}
${panel('Faction Web','⌘',`${webGraphic(false)}<div class="legend"><i class="l friend"></i>Friendly <i class="l neutral"></i>Neutral/Unknown <i class="l enemy"></i>Hostile</div>`,'<button data-page="web">VIEW FULL WEB</button>')}
${panel('Active Clocks','⌛',`<div class="clocklist">${state.clocks.slice(0,4).map(clockMini).join('')}</div>`,'<button data-page="clocks">VIEW ALL</button>')}
${panel('Next Session','⚔',`<div class="checklist">${state.next.map((x,i)=>`<label><input type="checkbox" data-check="${i}" ${state.checked[i]?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div>`,'<button data-page="notes">NOTES</button>')}
${panel('Action Oracle','⚄',`<div class="quickoracle"><label>Position<select id="qPos"><option>Controlled</option><option selected>Risky</option><option>Desperate</option></select></label><label>Effect<select id="qEff"><option>Limited</option><option selected>Standard</option><option>Great</option></select></label><label>Dice<input id="qDice" type="number" min="0" max="6" value="2"></label><button id="quickRoll">ROLL</button><div id="quickResult" class="resultline">Ready.</div></div>`,'<button data-page="oracle">OPEN ORACLE</button>')}
${panel('Score Engine','⚔',`<div class="scorequick"><label>Plan Type<select id="homePlan"><option>Stealth</option><option>Assault</option><option>Deception</option><option>Occult</option><option>Social</option><option>Transport</option></select></label><p id="homeHook">${pick(scoreHooks)}</p><button id="newHomeHook">GENERATE SCORE SPARK</button></div>`,'<button data-page="score">BUILD FULL SCORE</button>')}
${panel('Key NPCs','☻',`<div class="facequick">${faces.slice(0,4).map(f=>`<button data-page="faces"><span class="miniavatar">${f.name[0]}</span><span><b>${f.name}</b><small>${f.role}</small></span></button>`).join('')}</div>`,'<button data-page="faces">VIEW ALL NPCs</button>')}
${panel('Doskval','⌖',`<div class="minimap"><div class="river-mini"></div>${['Six Towers','Charterhall','Coalridge','The Docks','Nightmarket',"Crow’s Foot"].map((d,i)=>`<button class="m${i}" data-page="map">${d}</button>`).join('')}<span class="compass">N<br>✦</span></div>`,'<button data-page="map">EXPLORE CITY</button>')}
</div>`}
function oraclePage(){return pageHead('Action Oracle','Resolve any action')+`<div class="two"><section class="panel form"><h3>Position</h3><div class="choices" id="posBtns">${['Controlled','Risky','Desperate'].map(x=>`<button data-val="${x}" class="${x==='Risky'?'selected':''}">${x}</button>`).join('')}</div><h3>Effect</h3><div class="choices" id="effBtns">${['Limited','Standard','Great'].map(x=>`<button data-val="${x}" class="${x==='Standard'?'selected':''}">${x}</button>`).join('')}</div><h3>Action Rating</h3><div class="pips" id="diceBtns">${[0,1,2,3,4,5,6].map(x=>`<button data-val="${x}" class="${x===2?'selected':''}">${x}</button>`).join('')}</div><label><input type="checkbox" id="assist"> Assisted +1d</label><label><input type="checkbox" id="push"> Push / Devil’s Bargain +1d</label><button class="primary big" id="resolve">ROLL & RESOLVE</button></section><section class="panel oracleout" id="oracleOut"><div class="bigicon">⚄</div><h2>Ready</h2><p>Set position, effect and dice.</p></section></div>`}
function rollPool(n){if(n<=0){let d=[1+Math.floor(Math.random()*6),1+Math.floor(Math.random()*6)];return {dice:d,result:Math.min(...d),critical:false,zero:true}}let d=Array.from({length:n},()=>1+Math.floor(Math.random()*6));return {dice:d,result:Math.max(...d),critical:d.filter(x=>x===6).length>=2,zero:false}}
function outcome(pos,eff,r){let title,txt,cls='';if(r.critical){title='CRITICAL';txt='Exceptional success. Consider increased effect or an extra benefit.';cls='good'}else if(r.result===6){title='FULL SUCCESS';txt=`They do it cleanly with ${eff.toLowerCase()} effect.`;cls='good'}else if(r.result>=4){title='PARTIAL SUCCESS';cls='mixed';txt=pos==='Controlled'?'They succeed with a minor consequence or reduced effect.':pos==='Risky'?'They succeed, but there is a real consequence.': 'They succeed, but the desperate consequence is severe.'}else{title='BAD OUTCOME';cls='bad';txt=pos==='Controlled'?'Withdraw or press on from a riskier position.':pos==='Risky'?'Things go badly: serious consequence or lost opportunity.':'The worst comes to pass: severe consequence or major complication.'}return {title,txt,cls}}
function factionsPage(){return pageHead('Faction Ledger','Crew standing and starting city pressure')+`<input id="fSearch" class="search" placeholder="Search factions…"><div class="cards" id="fCards">${factions.map((f,i)=>`<section class="panel factioncard" data-fcard><div class="ficon">${f.icon}</div><h3>${f.name}</h3><p><b>Tier ${f.tier} · ${f.hold} hold</b></p><p>${f.canon}</p>${f.campaign?`<p class="campaign"><b>Campaign:</b> ${f.campaign}</p>`:''}<div class="standing">The Sneaks <b>${(state.factionStatus[f.name]??f.crew)>0?'+':''}${state.factionStatus[f.name]??f.crew}</b><button data-fidx="${i}" data-d="-1">−</button><button data-fidx="${i}" data-d="1">+</button></div></section>`).join('')}</div>`}
function webPage(){return pageHead('Faction Web','Canon starts the city; your campaign rewrites it')+`<section class="panel fullweb">${webGraphic(true)}<p class="hint">Tap a faction to inspect and edit its relationship with another faction.</p></section><section class="panel" id="relEditor"><h3>Relationship Editor</h3><div class="relform"><select id="relA">${factions.map(f=>`<option>${f.name}</option>`).join('')}</select><select id="relB">${factions.map((f,i)=>`<option ${i===1?'selected':''}>${f.name}</option>`).join('')}</select><select id="relStatus"><option>unknown</option><option>allied</option><option>friendly</option><option>rival</option><option>hostile</option><option>war</option></select><input id="relWhy" placeholder="Why? Canon or campaign event…"><button id="saveRel">SAVE RELATIONSHIP</button></div><div id="relRead" class="note"></div></section>`}
function mapPage(){return pageHead('Doskval Map Desk','Districts become situations')+`<div class="two maplayout"><section class="panel bigmap"><div class="mapriver"></div>${districts.map((d,i)=>`<button class="district d${i}" data-district="${i}">${d[0]}</button>`).join('')}<span class="compass bigc">N<br>✦</span></section><section class="panel" id="districtInfo"><h3>Select a district</h3><p>Tap the map for atmosphere and a score spark.</p></section></div>`}
function clocksPage(){return pageHead('Active Clocks','Visible pressure makes the city move')+`<button id="addClock">+ ADD CLOCK</button><div class="cards clocks">${state.clocks.map((c,i)=>`<section class="panel"><h3>${esc(c.name)}</h3><div class="clockbig" style="--p:${c.filled/c.size*360}deg"><i></i></div><p>${c.filled} / ${c.size}</p><div class="clockcontrols"><button data-ci="${i}" data-cd="-1">−</button><button data-ci="${i}" data-cd="1">+</button><button data-del="${i}">Remove</button></div></section>`).join('')}</div>`}
function facesPage(){return pageHead('Faces in the Fog','People, pressure and personality')+`<input id="faceSearch" class="search" placeholder="Search NPCs…"><div class="cards" id="faceCards">${faces.map(f=>`<section class="panel face" data-face><div class="avatar">${f.name[0]}</div><h3>${f.name}</h3><span class="badge">${f.kind}</span><p><b>${f.role}</b></p><p>${f.details||''}</p><p><b>Voice:</b> ${f.voice}</p><p><b>Tell:</b> ${f.tell}</p><p><b>Wants:</b> ${f.want}</p><p class="history"><b>History:</b> ${f.history}</p></section>`).join('')}</div>`}
function scorePage(){return pageHead('Score Engine','Plan the job, then throw them into it')+`<div class="two"><section class="panel form"><label>Plan Type<select id="planType"><option>Assault</option><option>Deception</option><option selected>Stealth</option><option>Occult</option><option>Social</option><option>Transport</option></select></label><label>Plan Detail<input id="planDetail" placeholder="Target, point of attack, method, route…"></label><label>Major Advantages<input id="adv" type="number" min="0" max="5" value="0"></label><label>Major Disadvantages<input id="dis" type="number" min="0" max="5" value="0"></label><button id="engage" class="primary">ROLL ENGAGEMENT</button><button id="spark">GENERATE SCORE SPARK</button></section><section class="panel oracleout"><h3 id="scoreHook">${pick(scoreHooks)}</h3><div id="engageResult" class="resultline">Engagement starts at 1d, then add/subtract major advantages and disadvantages.</div><button id="scoreComp">SUGGEST COMPLICATION</button><div id="scoreCompOut" class="note"></div></section></div>`}
function gatherPage(){return pageHead('Gather Information','Ask better questions; get sharper answers')+`<div class="cards"><section class="panel"><h3>Quellyn · Six Towers</h3><p>Occult phenomena, strange ingredients, spirits, arcane objects and Six Towers rumours.</p><button id="quellynLead">ASK QUELLYN FOR A LEAD</button><div id="lead" class="note"></div></section><section class="panel"><h3>Questions that move play</h3><p>What is really going on here?</p><p>What should I be worried about?</p><p>Where is the weakness?</p><p>Who benefits if this goes wrong?</p><p>What opportunity is everyone overlooking?</p></section></div>`}
function notesPage(){return pageHead('Session Notes','Remember what the city made true')+`<section class="panel"><textarea id="notes" class="notes" placeholder="Scores, NPC voices, promises, betrayals, clocks, consequences…">${esc(state.notes)}</textarea><p class="hint">Auto-saves on this device.</p></section>`}
function advancePage(){return pageHead('Advance Time','Let the city move when the crew is not looking')+`<div class="two"><section class="panel"><h3>City Pulse</h3><p>Advance time once after a meaningful stretch of downtime or whenever you want the factions to feel alive.</p><button id="advanceCity" class="primary big">ADVANCE THE CITY</button><label>Pressure strength<select id="pulseStrength"><option value="1">Quiet</option><option value="2" selected>Normal</option><option value="3">Violent</option></select></label></section><section class="panel"><h3>What may move</h3><p>One or more active clocks can advance. A faction may make a move. A new development is recorded on the home screen.</p><div id="pulseResult" class="note">The city is waiting.</div></section></div>`}
function settingsPage(){return pageHead('Settings','Your table, your canon')+`<div class="cards"><section class="panel"><h3>Campaign Baseline</h3><p><b>Published canon</b> establishes the starting city. Campaign events override it. GM-created material remains clearly marked.</p></section><section class="panel"><h3>Visual Direction</h3><p>Locked: industrial gothic, hooded Sneaks figure, dense GM-console layout, ethereal green/electric-blue accents.</p></section><section class="panel"><h3>Reset Local Campaign Data</h3><p>This clears clocks, relationship overrides, notes and session checklist on this device.</p><button id="resetData">RESET LOCAL DATA</button></section></div>`}
function crewPage(){return pageHead('The Sneaks','Shadows in a city that remembers')+`<section class="panel crewdetail">${hood}<div><h2>The Sneaks</h2><p>Shadows crew.</p><p><b>Known campaign relationships:</b> Gray Cloaks favorable; Wraith tribute faithfully paid for Nightmarket; Grinders angered by theft; Quellyn trusted after two clean ingredient jobs.</p><p>Everything else should be earned at the table rather than invented as campaign fact.</p></div></section>`}
function pageHead(t,s){return `<div class="pagehead"><div><p>DOSKVAL · PRIVATE GM LEDGER</p><h2>${t}</h2><span>${s}</span></div><b>☾ ✦ ☽</b></div>`}
function render(){document.querySelector('#nav').innerHTML=navHTML();let m=document.querySelector('#main');let p=state.page; m.innerHTML=p==='home'?home():p==='oracle'?oraclePage():p==='score'?scorePage():p==='factions'?factionsPage():p==='web'?webPage():p==='map'?mapPage():p==='clocks'?clocksPage():p==='faces'?facesPage():p==='gather'?gatherPage():p==='notes'?notesPage():p==='advance'?advancePage():p==='settings'?settingsPage():p==='crew'?crewPage():home();wire();}
function wire(){$$('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-check]').forEach(c=>c.onchange=()=>{state.checked[c.dataset.check]=c.checked;save()});
$('#newHomeHook')&&($('#newHomeHook').onclick=()=>$('#homeHook').textContent=pick(scoreHooks));
$('#quickRoll')&&($('#quickRoll').onclick=()=>{let r=rollPool(+$(`#qDice`).value),o=outcome($('#qPos').value,$('#qEff').value,r);$('#quickResult').innerHTML=`<b class="${o.cls}">${o.title}</b> · [${r.dice.join(', ')}] — ${o.txt}`});
if($('#resolve')){let pos='Risky',eff='Standard',dice=2;$$('#posBtns button').forEach(b=>b.onclick=()=>{pos=b.dataset.val;$$('#posBtns button').forEach(x=>x.classList.toggle('selected',x===b))});$$('#effBtns button').forEach(b=>b.onclick=()=>{eff=b.dataset.val;$$('#effBtns button').forEach(x=>x.classList.toggle('selected',x===b))});$$('#diceBtns button').forEach(b=>b.onclick=()=>{dice=+b.dataset.val;$$('#diceBtns button').forEach(x=>x.classList.toggle('selected',x===b))});$('#resolve').onclick=()=>{let n=dice+($('#assist').checked?1:0)+($('#push').checked?1:0),r=rollPool(n),o=outcome(pos,eff,r);$('#oracleOut').innerHTML=`<div class="bigicon">⚄</div><div class="diceout">${r.dice.map(x=>`<i>${x}</i>`).join('')}</div><h2 class="${o.cls}">${o.title}</h2><p>${o.txt}</p><button id="suggestCon">SUGGEST A CONSEQUENCE</button><div id="conOut" class="note"></div>`;$('#suggestCon').onclick=()=>$('#conOut').textContent=pick(complications)}}
$$('[data-fidx]').forEach(b=>b.onclick=()=>{let f=factions[+b.dataset.fidx],v=state.factionStatus[f.name]??f.crew;state.factionStatus[f.name]=Math.max(-3,Math.min(3,v+(+b.dataset.d)));save();render()});
$('#fSearch')&&($('#fSearch').oninput=e=>$$('[data-fcard]').forEach(c=>c.hidden=!c.innerText.toLowerCase().includes(e.target.value.toLowerCase())));
$('#faceSearch')&&($('#faceSearch').oninput=e=>$$('[data-face]').forEach(c=>c.hidden=!c.innerText.toLowerCase().includes(e.target.value.toLowerCase())));
function readRel(){if(!$('#relA'))return;let a=$('#relA').value,b=$('#relB').value,r=getRel(a,b);$('#relStatus').value=r.status;$('#relWhy').value=r.why;$('#relRead').innerHTML=`<b>${a} ↔ ${b}</b><br>${r.status.toUpperCase()} — ${esc(r.why)}`};$('#relA')&&($('#relA').onchange=readRel,$('#relB').onchange=readRel,$('#saveRel').onclick=()=>{let a=$('#relA').value,b=$('#relB').value;if(a===b)return;state.rels[relationKey(a,b)]={status:$('#relStatus').value,why:$('#relWhy').value||'Campaign update.'};save();readRel();},readRel());
$$('[data-district]').forEach(b=>b.onclick=()=>{let d=districts[+b.dataset.district];$('#districtInfo').innerHTML=`<h3>${d[0]}</h3><p>${d[1]}</p><p><b>Score spark:</b> ${pick(scoreHooks)}</p>`});
$$('[data-ci]').forEach(b=>b.onclick=()=>{let c=state.clocks[+b.dataset.ci];c.filled=Math.max(0,Math.min(c.size,c.filled+(+b.dataset.cd)));save();render()});$$('[data-del]').forEach(b=>b.onclick=()=>{state.clocks.splice(+b.dataset.del,1);save();render()});$('#addClock')&&($('#addClock').onclick=()=>{let name=prompt('Clock name?');if(!name)return;let size=+(prompt('Segments: 4, 6, or 8?','6')||6);if(![4,6,8].includes(size))size=6;state.clocks.push({name,size,filled:0});save();render()});
$('#spark')&&($('#spark').onclick=()=>$('#scoreHook').textContent=pick(scoreHooks));$('#scoreComp')&&($('#scoreComp').onclick=()=>$('#scoreCompOut').textContent=pick(complications));$('#engage')&&($('#engage').onclick=()=>{let n=Math.max(0,1+(+$('#adv').value)-(+$('#dis').value)),r=rollPool(n);let txt=r.critical?'Critical: beyond the first obstacle.':r.result===6?'Controlled position.':r.result>=4?'Risky position.':'Desperate position.';$('#engageResult').innerHTML=`Rolled ${n}d: [${r.dice.join(', ')}] · <b>${txt}</b>`});
$('#quellynLead')&&($('#quellynLead').onclick=()=>$('#lead').textContent=pick(['A spirit has begun repeating a name that belongs to someone still alive.','A fungus in her garden only blooms near something recently possessed.','Someone has been buying rare binding salts in quantities too large for private use.','A Six Towers house that should be empty has started producing warm chimney smoke.']));
$('#notes')&&($('#notes').oninput=e=>{state.notes=e.target.value;save()});
$('#advanceCity')&&($('#advanceCity').onclick=()=>{let strength=+$('#pulseStrength').value,moved=[];for(let n=0;n<strength;n++){if(state.clocks.length){let c=pick(state.clocks);if(c.filled<c.size){c.filled++;moved.push(`${c.name} → ${c.filled}/${c.size}`)}}}let dev=pick(['Bluecoat attention shifts toward a new rumour.','A faction sends feelers through intermediaries.','A whispered opportunity appears in Nightmarket.','Crow’s Foot tension produces a new casualty.','An occult disturbance is noticed in Six Towers.','Someone begins asking careful questions about The Sneaks.']);state.developments.unshift(dev);state.developments=state.developments.slice(0,8);state.day=(state.day||0)+1;save();$('#pulseResult').innerHTML=`<b>City pulse ${state.day}</b><br>${moved.join('<br>')||'No clock advanced.'}<br>${dev}`});
$('#resetData')&&($('#resetData').onclick=()=>{if(confirm('Reset Doskval local campaign data on this device?')){localStorage.removeItem('doskval-v3');state=JSON.parse(JSON.stringify(defaults));render()}});
}
render();