// Deep lore pass — Core v8.2 + established Sneaks campaign facts.
(function(){
const lore={
'The Billhooks':{tier:'II',hold:'Weak',category:'Underworld',summary:'A savage family gang of butchers, extortionists and pit-fighters.',npcs:[['Tarvul','Leader; serving life in Ironhook. Savage, arrogant, family-minded.'],['Erin','Tarvul’s sister and captain; confident, deadly and ambitious.'],['Coran','Tarvul’s son; fierce, loyal and quiet.']],allies:['Bluecoats','Ministry of Preservation'],enemies:['Ulf Ironborn','The Lost'],clocks:['Terrorize magistrates to pardon members in prison · 8']},
'Bluecoats':{tier:'III',hold:'Strong',category:'Institutions',summary:'Doskvol’s corrupt and violent City Watch — effectively the meanest gang in the city.',npcs:[['Commander Clelland','Chief commissioner; corrupt, cruel and arrogant.'],['Captain Michter','Chief instructor; ambitious, fierce and confident.'],['Captain Vale','Quartermaster; loyal, insightful and quiet.']],allies:['City Council','The Billhooks','The Crows','Ironhook Prison','Lord Scurlock','The Unseen'],enemies:['Imperial Military','Many criminal organizations'],clocks:['Procure bigger budget, military arms & equipment · 8']},
'The Crows':{tier:'II',hold:'Weak',category:'Underworld',summary:'An old Crow’s Foot gang of gambling and extortion rackets, destabilized by Roric’s death.',npcs:[['Lyssa','Current boss; killed Roric and now struggles to secure her leadership.'],['Bell','A Crow enforcer and important gang face.'],['Roric','Former boss. Dead, but the mystery of his ghost and murder still hangs over Crow’s Foot.']],allies:['Bluecoats'],enemies:['Lampblacks','Red Sashes'],clocks:['Secure Lyssa’s leadership / dominate Crow’s Foot']},
'The Lampblacks':{tier:'II',hold:'Weak',category:'Underworld',summary:'Former lamp-lighters turned criminals after electric lighting destroyed their trade; at war with the Red Sashes.',npcs:[['Bazso Baz','Gang boss and veteran underworld operator; central figure in the Crow’s Foot war.'],['Pickett','Lampblack gang member and useful faction face.'],['Henner','Lampblack gang member and useful faction face.']],allies:['Gondoliers','Fog Hounds'],enemies:['Red Sashes'],clocks:['Destroy the Red Sashes / win the Crow’s Foot war']},
'The Red Sashes':{tier:'II',hold:'Weak',category:'Underworld',summary:'An Iruvian sword school expanded into crime, with noble and diplomatic connections.',npcs:[['Mylera Klev','Leader; shrewd, ruthless, educated and an art collector.']],allies:['Iruvian Consulate','Path of Echoes','Dockers','Cabbies','Inspectors'],enemies:['Lampblacks','Bluecoats','Gondoliers'],clocks:['Destroy the Lampblacks · 8','Become ward boss of Crow’s Foot · 8']},
'The Wraiths':{tier:'II',hold:'Weak',category:'Underworld',summary:'Masked thieves and spies who hunt primarily in Silkshore and Nightmarket, specializing in luxury theft and intelligence.',npcs:[['Slate','Leader; sophisticated, daring and secretive.'],['Loop','Appraisal expert; obsessive, moody and secretive.']],allies:['Cabbies'],enemies:['Bluecoats','Inspectors','The Hive'],clocks:['Recruit expert thieves · 8','Secure an arcane ally · 6'],campaign:'The Sneaks have faithfully paid the Wraiths tribute for access to Nightmarket.'},
'Gray Cloaks':{tier:'II',hold:'Strong',category:'Underworld',summary:'Former Bluecoats framed and expelled from the Watch, now operating as criminals from Six Towers.',npcs:[['Nessa','Leader; scrupulous and daring.'],['Hutch','Second; brash and fierce.']],allies:['Inspectors'],enemies:['Bluecoats','Lord Strangford'],clocks:['Secure Six Towers as their turf · 8','Avenge their expulsion · 8'],campaign:'They favor The Sneaks. The exact character-creation reason is deliberately unknown.'},
'The Grinders':{tier:'II',hold:'Weak',category:'Underworld',summary:'Vicious former Lockport dockers and leviathan-blood refinery workers raising money for a revolutionary warship.',npcs:[['Hutton','Leader; confident and volatile.'],['Sercy','Second; defiant and physically disabled.'],['Derret','Toughest gang member; huge and shrewd.']],allies:['Ulf Ironborn','Dockers'],enemies:['Bluecoats','Imperial Military','Leviathan Hunters','Sailors','Silver Nails'],clocks:['Raise a crew, steal a war ship · 12','Fill war treasury · 12'],campaign:'The Grinders are angry with The Sneaks after the crew stole from them.'},
'The Dimmer Sisters':{tier:'II',hold:'Strong',category:'Underworld',summary:'House-bound occult recluses quietly consolidating Doskvol’s trade in captured spirits and spirit essences.',npcs:[['Roslyn','Patient, loyal and arcane servant who deals with outsiders.'],['Irelen','Loyal, enigmatic and obsessive spark-craft tinkerer.']],allies:['Forgotten Gods','The Foundation'],enemies:['Spirit Wardens','The Reconciled'],clocks:['Dominate the spirit trade · 6','Obtain arcane secrets · 4']},
'Gondoliers':{tier:'III',hold:'Strong',category:'Labor & Trade',summary:'Ancient canal operators trusted by citizens with supernatural problems and keepers of submerged occult knowledge.',npcs:[['Eisele','Leader; serene, knowledgeable and fearless.'],['Griggs','Chief Whisper; strange, ruthless and haunted.']],allies:['Lampblacks','Citizenry'],enemies:['Red Sashes','Spirit Wardens'],clocks:['Investigate desecrated hollows · 8','Destroy spirit wells · 4']},
'The Fog Hounds':{tier:'I',hold:'Weak',category:'Underworld',summary:'Hard-bitten Void Sea veterans turned smugglers, seeking a reliable patron.',npcs:[['Margette Vale','Leader; quiet, cold and fearless.'],['Bear','Second; fierce, moody and brash.'],['Goldie','Navigator; calculating, patient and confident.']],allies:['Dockers','Lampblacks'],enemies:['Bluecoats','The Vultures'],clocks:['Eliminate rival smugglers · 8','Obtain a regular patron · 6']},
'Spirit Wardens':{tier:'IV',hold:'Strong',category:'Institutions',summary:'Anonymous bronze-masked hunters who destroy rogue spirits and operate Bellweather Crematorium.',npcs:[['Bakoros','A Warden code-name that may refer to several people; sometimes lectures at Doskvol Academy.']],allies:['Church of Ecstasy','Deathlands Scavengers'],enemies:['Dimmer Sisters','Gondoliers','Lord Scurlock','Silver Nails','The Unseen','Path of Echoes','The Reconciled'],clocks:['Uncover the infiltrators · 8']},
'Lord Scurlock':{tier:'III',hold:'Strong',category:'Underworld',summary:'An ancient noble, possibly a vampire or sorcerer, powerful enough to count as a faction by himself.',npcs:[['Lord Scurlock','Enigmatic, cold, arcane and old-fashioned; bound by ancient magic to Setarra.'],['Setarra','A demon bound to Scurlock in an ancient relationship of shifting master and servant.']],allies:['City Council','Bluecoats','Inspectors','Forgotten Gods'],enemies:['Spirit Wardens','Immortal Emperor'],clocks:['Fulfill debt to Setarra · 12','Obtain arcane secrets · 6']},
'The Silver Nails':{tier:'III',hold:'Strong',category:'Underworld',summary:'Severosi mercenaries and renowned ghost killers pushing into the forbidden Lost District.',npcs:[['Seresh','Leader; bold, brash and defiant.'],['Tuhan','Lead scout; bold, cunning and charming.']],allies:['Imperial Military','Sailors','Severosi Consulate'],enemies:['Circle of Flame','Grinders','Skovlan Consulate','Skovlander Refugees','Spirit Wardens'],clocks:['Destroy spirits in the Lost District · 8','Control the Lost District · 8']},
'Sparkwrights':{tier:'IV',hold:'Strong',category:'Institutions',summary:'Engineers who maintain the lightning barriers and pursue dangerous spark-craft research.',npcs:[['Una Farros','Charterhall University instructor; curious, vain and famous.']],allies:['City Council','Leviathan Hunters','Ministry of Preservation'],enemies:['Path of Echoes','The Reconciled','The Foundation'],clocks:['Develop alternative fuel · 12']},
'The Unseen':{tier:'IV',hold:'Strong',category:'Underworld',summary:'A secret criminal enterprise whose arcane protections erase knowledge of its members.',npcs:[['The Tower','Secret leader of the Unseen.'],['The Star','Captain of the Unseen.'],['Grull','Ambitious mid-level thug operating undercover as a coach driver.']],allies:['Bluecoats','Ironhook Prison','Forgotten Gods','Cyphers'],enemies:['Ink Rakes','The Hive','Spirit Wardens'],clocks:['Infiltrate the Spirit Wardens · 8','Expand into other cities · 8']},
'Ulf Ironborn':{tier:'I',hold:'Strong',category:'Underworld',summary:'A brutal newly-arrived Skovlander carving out turf through savage smash-and-grab operations.',npcs:[['Ulf Ironborn','Leader; ruthless, savage and bold.'],['Havid','Second; ruthless, volatile and shrewd.']],allies:['Grinders'],enemies:['Citizens of Coalridge','Billhooks'],clocks:['Carve out gang territory · 6','Rise in Tier · 4']},
'Church of Ecstasy':{tier:'IV',hold:'Strong',category:'The Fringe',summary:'Doskvol’s powerful state religion, devoted to the life of the body and hostile to the corrupted spirit world.',npcs:[['Elder Rowan','Leader; devout, resolute and visionary.'],['Preceptor Dunvil','Arcane researcher; unorthodox, obsessive and enigmatic.']],allies:[],enemies:['The Reconciled'],clocks:['Unlock the secret of ascension · 12','Eliminate the Reconciled · 12']}
};
const briefs={
'The Hive':'Tier IV merchant guild secretly trading contraband, marked by the golden bee.',
'The Circle of Flame':'Tier III secret society of antiquarians and scholars hiding extortion, graft, vice and murder.',
'The Lost':'Tier I street-toughs and ex-soldiers who protect the downtrodden.',
'Imperial Military':'Tier VI armed forces of the Imperium stationed in Doskvol.',
'City Council':'Tier V elite noble rulers of the city government.',
'Leviathan Hunters':'Tier V captains and crews who hunt titanic demons of the Void Sea for blood.',
'Ministry of Preservation':'Tier V Imperial body controlling inter-city transportation and vital resources.',
'Ironhook Prison':'Tier IV prison where criminal organizations continue to operate from inside.',
'Inspectors':'Tier III criminal investigators with an unusual reputation for ethics and integrity.',
'Iruvian Consulate':'Tier III diplomatic power representing Iruvia in Doskvol.',
'Skovlan Consulate':'Tier III diplomatic presence representing Skovlan.',
'The Brigade':'Tier II firefighters, loved for heroism and hated for looting and extortion.',
'Dagger Isles Consulate':'Tier I diplomatic presence for the Dagger Isles.',
'Severosi Consulate':'Tier I diplomatic presence for Severos.',
'The Foundation':'Tier IV ancient order of architects and builders with frightening reach.',
'Dockers':'Tier III hard-bitten laborers who work Doskvol’s docks.',
'Laborers':'Tier III organized working people of the city.',
'Sailors':'Tier III captains and crews of merchant and Imperial Navy ships.',
'Cabbies':'Tier II public coach operators and goat breeders with an excellent gossip network.',
'Cyphers':'Tier II messenger guild sworn to secrecy about messages and clients.',
'Ink Rakes':'Tier II journalists, muck-rakers and newspaper publishers.',
'Rail Jacks':'Tier II protectors of electro-trains against deathlands spirits; union talk is growing.',
'Servants':'Tier II network of domestic workers with access to private lives and households.',
'The Forgotten Gods':'Tier III loose collection of old cults serving pre-cataclysm gods, demons and darker things.',
'The Horde':'Tier III mass of hollows united by an unknown power and purpose.',
'The Path of Echoes':'Tier III mystery cult revering the ancients and defying spirit laws.',
'The Reconciled':'Tier III association of ancient spirits that have not gone feral.',
'Skovlander Refugees':'Tier III survivors of the Unity War pushed toward criminal opportunities by exclusion.',
'Deathlands Scavengers':'Tier II convicts and freelancers who survive beyond the lightning barriers.',
'The Weeping Lady':'Tier II charity and pseudo-religion devoted to Lady Devera and the poor.'};
const contacts=[
{name:'Quellyn',group:'Whisper contact · Campaign friend',role:'Witch, healer and seer',sentence:'A young witch in Six Towers; a competent healer wanted by the Spirit Wardens. In this campaign she lives in a cottage behind a low stone fence, with a mostly fungal garden sustained by a little real magic and drying herbs overhead.',status:'Friend'},
{name:'Flint',group:'Whisper contact · Campaign rival',role:'Spirit trafficker',sentence:'A weird, calculating and suspicious spirit trafficker operating from a condemned Six Towers manor; a source of unusual arcane supplies or an occult rival.',status:'Rival'},
{name:'Stazia',group:'Leech contact · Campaign friend',role:'Apothecary',sentence:'An apothecary who may have one foot in legitimate alchemy and another in the underworld; in the campaign she can source potent substances, though not always predictably.',status:'Friend'},
{name:'Malista',group:'Leech contact · Campaign rival',role:'Priestess',sentence:'A priestess devoted to a forgotten god; campaign evidence places her in suspicious meetings with an unknown figure.',status:'Rival'},
{name:'Telda',group:'Lurk contact · Campaign friend',role:'Beggar',sentence:'A beggar who might have taught a Lurk the stealthy arts and who moves through a street-level information network; one of her beggar contacts has been detained by Bluecoats.',status:'Friend'},
{name:'Frake',group:'Lurk contact · Campaign rival',role:'Locksmith',sentence:'An expert locksmith — either the person you consult about impossible security or the master who builds locks specifically to defeat you.',status:'Rival'},
{name:'Fitz',group:'Shadows crew contact',role:'Collector',sentence:'A collector and aficionado of strange artifacts. In the campaign Fitz has heard of a rare leviathan-bone carving in Silkshore.',status:'Contact'},
{name:'Dowler',group:'Shadows crew contact',role:'Explorer',sentence:'An explorer, perhaps one of the rare deathlands scavengers to survive a sentence beyond the lightning barrier.',status:'Available'},
{name:'Laroze',group:'Shadows crew contact',role:'Bluecoat',sentence:'A Bluecoat who can plausibly serve as an informant inside the City Watch.',status:'Available'},
{name:'Amancio',group:'Shadows crew contact',role:'Deal broker',sentence:'A well-connected underworld deal broker known for neutrality.',status:'Available'},
{name:'Adelaide Phroaig',group:'Shadows crew contact',role:'Noble',sentence:'A noble connection who can open doors to elite targets and high-society scores.',status:'Available'},
{name:'Rigney',group:'Shadows crew contact',role:'Tavern owner',sentence:'A tavern owner and natural source of news, gossip and opportunities.',status:'Available'}
];
Object.entries(lore).forEach(([name,d])=>{let f=factions.find(x=>x.name===name);if(!f&&name==='Church of Ecstasy')f=factions.find(x=>x.name==='Church of Ecstasy');if(f)Object.assign(f,{canon:d.summary,lore:d});});
Object.entries(briefs).forEach(([name,summary])=>{const f=factions.find(x=>x.name===name);if(f&&!f.lore)f.lore={tier:f.tier,hold:f.hold,category:f.category||'Core faction',summary,npcs:[],allies:[],enemies:[],clocks:[]};});
window.DOSKVAL_LORE={lore,briefs,contacts};

function portrait(name){const initials=name.split(/\s+/).map(x=>x[0]).slice(0,2).join('');return `<span class="lorePortrait"><span>${initials}</span></span>`}
function npcCard(n,source='Published canon'){return `<article class="loreNpc">${portrait(n[0])}<div><h3>${esc(n[0])}</h3><small>${source}</small><p>${esc(n[1])}</p></div></article>`}
function contactsPage(){return `<div class="pagehead"><p>THE HUMAN WEB</p><h1>Contacts & Faces</h1><p>Character contacts, crew contacts, faction leaders and campaign people — with enough context to use them at the table.</p></div><section class="panel"><header><span>◉</span><h2>THE SNEAKS' CONTACT NETWORK</h2></header><div class="loreGrid">${contacts.map(c=>`<article class="loreNpc contact ${c.status.toLowerCase()}">${portrait(c.name)}<div><h3>${esc(c.name)}</h3><small>${esc(c.group)} · ${esc(c.status)}</small><b>${esc(c.role)}</b><p>${esc(c.sentence)}</p></div></article>`).join('')}</div></section><section class="panel"><header><span>♟</span><h2>FACTION LEADERS & IMPORTANT FACES</h2></header><div class="loreGrid">${Object.entries(lore).flatMap(([f,d])=>d.npcs.map(n=>npcCard([n[0],`${n[1]} — ${f}.`]))).join('')}</div></section>`}
function factionsPage(){return `<div class="pagehead"><p>THE CITY'S POWER STRUCTURE</p><h1>Faction Ledger</h1><p>Core-book baseline with Sneaks campaign changes layered on top.</p></div><div class="factionLoreGrid">${factions.map(f=>{const d=f.lore||{summary:f.canon,npcs:[],allies:[],enemies:[],clocks:[]};return `<article class="panel factionLore"><header><span>${f.icon||'◇'}</span><h2>${esc(f.name)}</h2><b>Tier ${esc(f.tier)} · ${esc(f.hold)}</b></header><p>${esc(d.summary||f.canon)}</p>${f.campaign?`<div class="campaignNote"><b>SNEAKS CAMPAIGN</b> ${esc(f.campaign)}</div>`:''}${d.npcs?.length?`<h3>Important Faces</h3>${d.npcs.map(n=>`<p><b>${esc(n[0])}</b> — ${esc(n[1])}</p>`).join('')}:''}${d.allies?.length?`<p><b>Allies:</b> ${esc(d.allies.join(', '))}</p>`:''}${d.enemies?.length?`<p><b>Enemies:</b> ${esc(d.enemies.join(', '))}</p>`:''}${d.clocks?.length?`<p><b>Faction clocks:</b> ${esc(d.clocks.join(' · '))}</p>`:''}</article>`}).join('')}</div>`}
const oldRender=window.render;
window.render=function(){oldRender();if(state.page==='faces')$('#main').innerHTML=contactsPage();if(state.page==='factions')$('#main').innerHTML=factionsPage();bindLore();};
function bindLore(){document.querySelectorAll('.loreNpc').forEach(x=>x.tabIndex=0)}
// Make the score engine draw from actual people/factions when asking for a new spark.
document.addEventListener('click',e=>{if(e.target&&e.target.id==='newHomeHook'){const fs=factions.filter(f=>f.lore);const f=pick(fs), people=f.lore?.npcs||[], who=people.length?pick(people)[0]:'a faction agent', places=['Nightmarket','Six Towers',"Crow’s Foot",'The Docks','Charterhall','Silkshore'];setTimeout(()=>{const el=document.getElementById('homeHook');if(el)el.textContent=`${who} of ${f.name} needs discreet work in ${pick(places)}. ${f.campaign||f.lore.summary}`},0)}});
window.render();
})();