// NPC / Faces clean rebuild. Self-contained: no dependency on the older NPC pipeline.
(function(){
const NPCS=[
{name:'Quellyn',role:'Witch · healer · seer',faction:'Unaffiliated',district:'Six Towers',group:'Crew Contacts',status:'Friend',source:'Core + campaign',desc:'A young witch and competent healer wanted by the Spirit Wardens. In this campaign she lives in a secluded Six Towers cottage behind a low stone fence, with drying herbs overhead and a mostly fungal garden sustained by a little real magic.',use:'Healing, occult insight, strange ingredients, ghost-related guidance.',connections:'The Sneaks — friendly; Spirit Wardens — danger; Six Towers — home.'},
{name:'Flint',role:'Spirit trafficker',faction:'Unaffiliated',district:'Six Towers',group:'Crew Contacts',status:'Rival',source:'Core + campaign',desc:'Weird, calculating and suspicious, Flint trades spirits from a condemned manor house. Useful for rare arcane supplies, dangerous information, or as an occult rival.',use:'Arcane contraband, spirit bottles, forbidden buyers.',connections:'Whisper contact; rival to the crew’s Whisper.'},
{name:'Stazia',role:'Apothecary',faction:'Unaffiliated',district:'Doskvol',group:'Crew Contacts',status:'Friend',source:'Core + campaign',desc:'An apothecary with the knowledge to move between legitimate alchemy and underworld chemistry. A dependable source of substances, remedies and technical advice.',use:'Alchemicals, recovery, poisons, formulas.',connections:'Leech contact; friendly to The Sneaks.'},
{name:'Malista',role:'Priestess',faction:'Forgotten Gods',district:'Doskvol',group:'Crew Contacts',status:'Rival',source:'Core + campaign',desc:'A priestess devoted to a forgotten god. Her rituals and loyalties make her an unpredictable occult rival, and campaign evidence places her in suspicious meetings.',use:'Cult lore, rituals, occult complications.',connections:'Leech contact; campaign rival.'},
{name:'Telda',role:'Beggar · street informant',faction:'Unaffiliated',district:'Doskvol',group:'Crew Contacts',status:'Friend',source:'Core + campaign',desc:'A beggar tied into the city’s street-level information network. She may have taught a Lurk the stealthy arts and hears things polite society never notices.',use:'Street rumours, hidden routes, watching targets.',connections:'Lurk contact; one of her beggar contacts has been detained by Bluecoats.'},
{name:'Frake',role:'Master locksmith',faction:'Unaffiliated',district:'Doskvol',group:'Crew Contacts',status:'Rival',source:'Core + campaign',desc:'An expert locksmith who understands security as an art. Frake can advise on impossible locks — or create the one lock designed specifically to defeat you.',use:'Locks, vaults, security systems, burglary complications.',connections:'Lurk contact; campaign rival.'},
{name:'Fitz',role:'Collector of strange artifacts',faction:'Unaffiliated',district:'Doskvol',group:'Crew Contacts',status:'Contact',source:'Core + campaign',desc:'A collector with a taste for unusual and occult objects. Fitz knows who owns what, who wants it, and which object is worth stealing.',use:'Score leads, artifact appraisal, buyers and collectors.',connections:'Shadows crew contact; heard of a rare leviathan-bone carving in Silkshore.'},
{name:'Dowler',role:'Explorer',faction:'Unaffiliated',district:'Deathlands',group:'Crew Contacts',status:'Available',source:'Core',desc:'An explorer with unusual experience beyond the lightning barriers, possibly one of the rare scavengers to survive a deathlands sentence.',use:'Deathlands routes, ruins, expeditions, maps.',connections:'Shadows crew contact.'},
{name:'Laroze',role:'Bluecoat informant',faction:'Bluecoats',district:'Doskvol',group:'Crew Contacts',status:'Available',source:'Core',desc:'A Bluecoat positioned to quietly make reports disappear, reveal patrol patterns, or feed the crew information from inside the Watch.',use:'Bluecoat intelligence, heat reduction, patrol information.',connections:'Shadows crew contact; Bluecoats.'},
{name:'Amancio',role:'Deal broker',faction:'Unaffiliated',district:'Doskvol',group:'Crew Contacts',status:'Available',source:'Core',desc:'A well-connected broker known for neutrality. Amancio is useful when two sides need to meet without immediately stabbing each other.',use:'Introductions, negotiations, neutral meetings, buyers.',connections:'Shadows crew contact.'},
{name:'Adelaide Phroaig',role:'Noble',faction:'Nobility',district:'Brightstone',group:'Crew Contacts',status:'Available',source:'Core',desc:'A noble connection who can open doors into elite society and point the crew toward opportunities among people with more money than caution.',use:'High-society access, elite targets, invitations, gossip.',connections:'Shadows crew contact.'},
{name:'Rigney',role:'Tavern owner',faction:'Unaffiliated',district:'Doskvol',group:'Crew Contacts',status:'Available',source:'Core',desc:'A tavern owner who hears the city talk. Rigney is a practical source for rumours, jobs, missing people, and who has been drinking with whom.',use:'Rumours, gossip, meeting place, score leads.',connections:'Shadows crew contact.'},
{name:'Lyssa',role:'Boss of the Crows',faction:'The Crows',district:"Crow’s Foot",group:'Faction Leaders',status:'Important',source:'Core',desc:'The new leader of the Crows after Roric’s death. Her position is powerful but contested, and every move she makes reshapes the struggle for Crow’s Foot.',use:'Crow’s Foot politics, jobs, pressure, betrayal.',connections:'The Crows; Bluecoats; Lampblacks and Red Sashes as rivals.'},
{name:'Roric',role:'Former boss of the Crows',faction:'The Crows',district:"Crow’s Foot",group:'Faction Figures',status:'Dead',source:'Core',desc:'The former boss of the Crows. Dead, but not politically irrelevant: questions around his murder and the fate of his ghost still haunt Crow’s Foot.',use:'Ghost plots, secrets, leverage against Lyssa.',connections:'The Crows; Lyssa; Crow’s Foot.'},
{name:'Bell',role:'Crow enforcer',faction:'The Crows',district:"Crow’s Foot",group:'Faction Figures',status:'Important',source:'Core',desc:'An important Crow enforcer and practical face of the gang when the crew deals with street-level Crows business.',use:'Crows muscle, messages, intimidation, local jobs.',connections:'The Crows.'},
{name:'Bazso Baz',role:'Boss of the Lampblacks',faction:'The Lampblacks',district:"Crow’s Foot",group:'Faction Leaders',status:'Important',source:'Core',desc:'Veteran underworld operator and leader of the Lampblacks. He is one of the central powers in the war for Crow’s Foot and knows how to turn desperate crews into useful assets.',use:'Jobs, gang politics, Crow’s Foot war, underworld introductions.',connections:'Lampblacks; Gondoliers; Fog Hounds; Red Sashes — war.'},
{name:'Pickett',role:'Lampblack gang member',faction:'The Lampblacks',district:"Crow’s Foot",group:'Faction Figures',status:'Active',source:'Core',desc:'A useful Lampblack face for street dealings, messages, retaliation and the day-to-day violence of the Crow’s Foot conflict.',use:'Gang contact, muscle, street information.',connections:'The Lampblacks.'},
{name:'Henner',role:'Lampblack gang member',faction:'The Lampblacks',district:"Crow’s Foot",group:'Faction Figures',status:'Active',source:'Core',desc:'A Lampblack gang member who can serve as a recognizable recurring face when the crew crosses the gang’s business.',use:'Gang contact, escorts, threats, local information.',connections:'The Lampblacks.'},
{name:'Mylera Klev',role:'Leader of the Red Sashes',faction:'The Red Sashes',district:"Crow’s Foot",group:'Faction Leaders',status:'Important',source:'Core',desc:'Shrewd, ruthless, educated and an art collector. Mylera leads the Red Sashes, an Iruvian sword school turned criminal faction.',use:'Duels, patronage, art, Iruvian connections, faction jobs.',connections:'Red Sashes; Iruvian Consulate; Path of Echoes; Lampblacks — war.'},
{name:'Slate',role:'Leader of the Wraiths',faction:'The Wraiths',district:'Nightmarket',group:'Faction Leaders',status:'Important',source:'Core',desc:'Sophisticated, daring and secretive. Slate leads the masked Wraiths and protects their interests in high-value theft and intelligence.',use:'Nightmarket pressure, stealth jobs, tribute, thieves’ politics.',connections:'Wraiths; Cabbies; hostile to Bluecoats, Inspectors and Hive.'},
{name:'Loop',role:'Appraisal expert',faction:'The Wraiths',district:'Nightmarket',group:'Faction Figures',status:'Active',source:'Core',desc:'Obsessive, moody and secretive, Loop evaluates valuables and strange objects for the Wraiths.',use:'Appraisal, stolen goods, rare-object rumours.',connections:'The Wraiths.'},
{name:'Nessa',role:'Leader of the Gray Cloaks',faction:'Gray Cloaks',district:'Six Towers',group:'Faction Leaders',status:'Friendly',source:'Core + campaign',desc:'Scrupulous and daring, Nessa leads the former Bluecoats who were framed and expelled from the Watch. The Gray Cloaks currently favor The Sneaks.',use:'Six Towers politics, Bluecoat secrets, covert muscle.',connections:'Gray Cloaks; Inspectors; The Sneaks — favorable.'},
{name:'Hutch',role:'Second of the Gray Cloaks',faction:'Gray Cloaks',district:'Six Towers',group:'Faction Figures',status:'Friendly',source:'Core',desc:'Brash and fierce, Hutch is Nessa’s second and a useful operational face for the Gray Cloaks.',use:'Muscle, Watch procedures, faction messages.',connections:'Gray Cloaks.'},
{name:'Hutton',role:'Leader of the Grinders',faction:'The Grinders',district:'Doskvol',group:'Faction Leaders',status:'Hostile',source:'Core + campaign',desc:'Confident and volatile, Hutton leads the revolutionary Grinders, raising money and force for their war against the Imperial leviathan-blood refineries.',use:'Retaliation, Skovlander politics, hijacking, revolutionary scores.',connections:'Grinders; Dockers; Ulf Ironborn; hostile to The Sneaks after the crew stole from them.'},
{name:'Sercy',role:'Second of the Grinders',faction:'The Grinders',district:'Doskvol',group:'Faction Figures',status:'Hostile',source:'Core',desc:'Defiant and hardened, Sercy is Hutton’s second and an important voice inside the Grinders.',use:'Faction negotiations, retaliation, revolutionary contacts.',connections:'The Grinders.'},
{name:'Derret',role:'Grinder bruiser',faction:'The Grinders',district:'Doskvol',group:'Faction Figures',status:'Hostile',source:'Core',desc:'Huge and shrewd, Derret is known as the toughest member of the Grinders — dangerous precisely because he is not merely muscle.',use:'Violence, intimidation, pursuit, faction enforcement.',connections:'The Grinders.'},
{name:'Eisele',role:'Leader of the Gondoliers',faction:'Gondoliers',district:'Canals',group:'Faction Leaders',status:'Important',source:'Core',desc:'Serene, knowledgeable and fearless. Eisele leads the ancient Gondoliers, who know the canals and the city’s submerged occult dangers better than anyone.',use:'Canals, spirits, occult investigations, discreet transport.',connections:'Gondoliers; Lampblacks; citizenry.'},
{name:'Griggs',role:'Chief Whisper',faction:'Gondoliers',district:'Canals',group:'Faction Figures',status:'Important',source:'Core',desc:'Strange, ruthless and haunted, Griggs is the Gondoliers’ chief Whisper and an authority on dangerous supernatural disturbances.',use:'Spirit wells, hauntings, occult threats.',connections:'Gondoliers.'},
{name:'Margette Vale',role:'Leader of the Fog Hounds',faction:'The Fog Hounds',district:'Canals',group:'Faction Leaders',status:'Important',source:'Core',desc:'Quiet, cold and fearless, Vale commands the Fog Hounds, Void Sea veterans turned smugglers who are seeking a reliable patron.',use:'Smuggling, canal routes, contraband, Void Sea experience.',connections:'Fog Hounds; Dockers; Lampblacks.'},
{name:'Bear',role:'Second of the Fog Hounds',faction:'The Fog Hounds',district:'Canals',group:'Faction Figures',status:'Active',source:'Core',desc:'Fierce, moody and brash, Bear serves as Vale’s second among the Fog Hounds.',use:'Smuggling muscle, shipboard contacts, threats.',connections:'The Fog Hounds.'},
{name:'Goldie',role:'Navigator',faction:'The Fog Hounds',district:'Canals',group:'Faction Figures',status:'Active',source:'Core',desc:'Calculating, patient and confident, Goldie knows routes through the canals and the northern smuggling lanes.',use:'Routes, navigation, supply caches, contraband logistics.',connections:'The Fog Hounds.'},
{name:'Lord Scurlock',role:'Ancient noble · occult power',faction:'Lord Scurlock',district:'Six Towers',group:'Faction Leaders',status:'Dangerous',source:'Core',desc:'An ancient noble of immense arcane power, possibly a vampire. Cold, enigmatic and obsessed with secrets that most people are wise enough to leave buried.',use:'Arcane secrets, supernatural patronage, terrifying favors.',connections:'City Council; Bluecoats; Inspectors; Setarra; Spirit Wardens — enemy.'},
{name:'Setarra',role:'Demon',faction:'Lord Scurlock',district:'Doskvol',group:'Faction Figures',status:'Dangerous',source:'Core',desc:'A demon bound to Scurlock by ancient magic in a relationship where master and servant may change depending on circumstance.',use:'Demonic bargains, arcane power, catastrophic complications.',connections:'Lord Scurlock.'},
{name:'Seresh',role:'Leader of the Silver Nails',faction:'The Silver Nails',district:'Doskvol',group:'Faction Leaders',status:'Important',source:'Core',desc:'Bold, brash and defiant, Seresh leads the Severosi mercenary ghost-killers known as the Silver Nails.',use:'Ghost hunting, mercenary work, Lost District expeditions.',connections:'Silver Nails; Imperial Military; Sailors; Severosi Consulate.'},
{name:'Tuhan',role:'Lead scout',faction:'The Silver Nails',district:'Doskvol',group:'Faction Figures',status:'Active',source:'Core',desc:'Bold, cunning and charming, Tuhan scouts for the Silver Nails and is well suited to dangerous expeditions.',use:'Scouting, deathlands, ghosts, reconnaissance.',connections:'The Silver Nails.'},
{name:'Ulf Ironborn',role:'Gang leader',faction:'Ulf Ironborn',district:'Coalridge',group:'Faction Leaders',status:'Dangerous',source:'Core',desc:'Ruthless, savage and bold, Ulf is a newly arrived Skovlander carving out turf through brutal smash-and-grab operations.',use:'Skovlander politics, protection rackets, violence.',connections:'Grinders — allies; Billhooks — enemies.'},
{name:'Havid',role:'Ulf’s second',faction:'Ulf Ironborn',district:'Coalridge',group:'Faction Figures',status:'Dangerous',source:'Core',desc:'Ruthless, volatile and shrewd, Havid helps turn Ulf’s rage into organized criminal pressure.',use:'Gang enforcement, negotiations, Skovlander street politics.',connections:'Ulf Ironborn.'},
{name:'Commander Clelland',role:'Chief commissioner',faction:'Bluecoats',district:'Doskvol',group:'Faction Leaders',status:'Dangerous',source:'Core',desc:'Corrupt, cruel and arrogant, Clelland commands the City Watch and embodies the Bluecoats at their institutional worst.',use:'City-wide law pressure, corruption, warrants, crackdowns.',connections:'Bluecoats; City Council.'},
{name:'Captain Michter',role:'Chief instructor',faction:'Bluecoats',district:'Doskvol',group:'Faction Figures',status:'Dangerous',source:'Core',desc:'Ambitious, fierce and confident, Michter trains Bluecoats and understands exactly how the Watch fights.',use:'Bluecoat tactics, elite patrols, training, enforcement.',connections:'Bluecoats.'},
{name:'Captain Vale',role:'Quartermaster',faction:'Bluecoats',district:'Doskvol',group:'Faction Figures',status:'Important',source:'Core',desc:'Loyal, insightful and quiet, Vale controls equipment and logistics inside the Watch.',use:'Weapons, uniforms, patrol resources, stolen Watch gear.',connections:'Bluecoats.'},
{name:'Elder Rowan',role:'Leader of the Church',faction:'Church of Ecstasy',district:'Brightstone',group:'Faction Leaders',status:'Important',source:'Core',desc:'Devout, resolute and visionary, Rowan leads the Church of the Ecstasy of the Flesh and pursues its deepest theological ambitions.',use:'Church politics, occult doctrine, elite religious influence.',connections:'Church of Ecstasy.'},
{name:'Preceptor Dunvil',role:'Arcane researcher',faction:'Church of Ecstasy',district:'Brightstone',group:'Faction Figures',status:'Important',source:'Core',desc:'Unorthodox, obsessive and enigmatic, Dunvil researches the arcane on behalf of the Church.',use:'Arcane research, forbidden doctrine, experimental rituals.',connections:'Church of Ecstasy.'},
{name:'Bakoros',role:'Spirit Warden code-name',faction:'Spirit Wardens',district:'Whitecrown',group:'Faction Figures',status:'Dangerous',source:'Core',desc:'A Warden code-name that may refer to more than one individual. Bakoros sometimes lectures at Doskvol Academy, offering one of the few visible handles on an otherwise anonymous order.',use:'Spirit Warden plots, Academy access, occult law.',connections:'Spirit Wardens.'},
{name:'Una Farros',role:'Spark-craft instructor',faction:'Sparkwrights',district:'Charterhall',group:'Faction Figures',status:'Important',source:'Core',desc:'Curious, vain and famous, Una Farros teaches at Charterhall University and represents the dangerous prestige of cutting-edge spark-craft.',use:'Technology, research, experimental devices, academic access.',connections:'Sparkwrights.'}
];
let active='Quellyn', filter='All NPCs', query='';
function h(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function hash(s){let n=0;for(const c of s)n=(n*31+c.charCodeAt(0))>>>0;return n}
function portrait(n,big=false){const v=hash(n.name), skin=['#bca18e','#9d806d','#c5a991','#806b60','#b59480','#6e6675'][v%6], hair=['#111316','#211a18','#151e24','#32241d','#090c11'][v%5], accent=['#79e4d3','#75b8e8','#b88ee8','#d58b65','#93d071'][v%5];const beard=v%3===0?`<path d="M28 55q22 26 44 0-4 30-22 31Q32 84 28 55" fill="${hair}"/>`:'';const long=v%4===0?`<path d="M19 45Q20 9 50 7q31 4 31 38l-10-15-6 42-15-52-14 51-7-41z" fill="${hair}"/>`:`<path d="M24 35Q30 10 50 10t26 25q-13-8-26-7-13-1-26 7z" fill="${hair}"/>`;const scar=v%5===0?`<path d="M61 30l-9 26" stroke="${accent}" opacity=".45"/>`:'';return `<svg class="npcPortraitSvg ${big?'big':''}" viewBox="0 0 100 120" role="img" aria-label="Portrait of ${h(n.name)}"><defs><radialGradient id="bg${v}" cx="50%" cy="28%"><stop offset="0" stop-color="${accent}" stop-opacity=".22"/><stop offset="1" stop-color="#05090c"/></radialGradient></defs><rect width="100" height="120" fill="url(#bg${v})"/><path d="M8 120q8-39 42-40 34 1 42 40" fill="#101a20"/><ellipse cx="50" cy="48" rx="24" ry="29" fill="${skin}"/>${long}${beard}${scar}<path d="M36 45l9-2m10 0l9 2" stroke="#182126" stroke-width="2"/><circle cx="42" cy="46" r="2" fill="${accent}"/><circle cx="58" cy="46" r="2" fill="${accent}"/><path d="M44 64q6 3 12 0" stroke="#634e4b" fill="none" stroke-width="1.5"/><path d="M0 102l100-9" stroke="${accent}" opacity=".12"/><path d="M7 111l86-8" stroke="#fff" opacity=".05"/></svg>`}
function filtered(){return NPCS.filter(n=>{const f=filter==='All NPCs'||n.group===filter;const q=(n.name+' '+n.role+' '+n.faction+' '+n.district+' '+n.status).toLowerCase().includes(query.toLowerCase());return f&&q})}
function card(n){return `<button class="npcTile ${active===n.name?'selected':''}" data-npc="${h(n.name)}"><div class="npcArt">${portrait(n)}</div><div class="npcTileMeta"><b>${h(n.name)}</b><span>${h(n.role)}</span><small>${h(n.faction)}</small></div></button>`}
function detail(n){return `<aside class="npcDetail"><div class="npcDetailHead"><div><small>${h(n.source)}</small><h2>${h(n.name)}</h2><p>${h(n.role)}</p></div><span class="npcStatus">${h(n.status)}</span></div><div class="npcHeroPortrait">${portrait(n,true)}</div><dl><dt>FACTION</dt><dd>${h(n.faction)}</dd><dt>LOCATION</dt><dd>${h(n.district)}</dd><dt>DESCRIPTION</dt><dd>${h(n.desc)}</dd><dt>USEFUL FOR</dt><dd>${h(n.use)}</dd><dt>KNOWN CONNECTIONS</dt><dd>${h(n.connections)}</dd></dl><div class="npcDetailActions"><button data-npc-action="notes">VIEW NOTES</button><button data-npc-action="favorite">★ MARK IMPORTANT</button><button data-npc-action="close">CLOSE PROFILE</button></div></aside>`}
function page(){const list=filtered(), cur=NPCS.find(n=>n.name===active)||list[0]||NPCS[0];return `<div class="npcRebuild"><header class="npcTop"><div><p>PEOPLE WHO MATTER IN DOSKVOL</p><h1>NPCs / Faces</h1></div><label class="npcSearch">⌕ <input id="npcSearchBox" value="${h(query)}" placeholder="Search people, factions, roles..."></label></header><div class="npcTabs">${['All NPCs','Crew Contacts','Faction Leaders','Faction Figures'].map(x=>`<button data-npcfilter="${x}" class="${filter===x?'active':''}">${x}<span>${NPCS.filter(n=>x==='All NPCs'||n.group===x).length}</span></button>`).join('')}</div><div class="npcLayout"><section class="npcDirectory"><header><h2>◉ THE HUMAN WEB</h2><span>${list.length} shown</span></header><div class="npcTiles">${list.map(card).join('')||'<p class="noNpc">No matching faces.</p>'}</div></section>${detail(cur)}</div></div>`}
function bind(){document.querySelectorAll('[data-npc]').forEach(b=>b.onclick=()=>{active=b.dataset.npc;draw()});document.querySelectorAll('[data-npcfilter]').forEach(b=>b.onclick=()=>{filter=b.dataset.npcfilter;draw()});const s=document.getElementById('npcSearchBox');if(s){s.oninput=()=>{query=s.value;draw(false)};setTimeout(()=>{const x=document.getElementById('npcSearchBox');if(x&&document.activeElement===s){x.focus();x.setSelectionRange(x.value.length,x.value.length)}},0)}}
function draw(scroll=true){const main=document.getElementById('main');if(!main)return;main.innerHTML=page();bind();if(scroll)main.scrollTop=0}
const prior=window.render;
window.render=function(){prior();if(typeof state!=='undefined'&&state.page==='faces')draw(false)};
// Repair immediately if the broken NPC screen is already open.
if(typeof state!=='undefined'&&state.page==='faces')draw(false);
})();