(()=>{
  const data=window.PLAYER_LEDGER;
  const nav=[['home','⌂','Home'],['score','⚔','Current Score'],['map','⌖','Known Map'],['faces','☻','Faces'],['factions','♟','Factions'],['clues','⌕','Clues'],['actions','✦','Actions']];
  const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let active='home',selectedDistrict=0;
  const head=(eyebrow,title,copy)=>`<header class="page-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div><p>${copy}</p></header>`;
  const districtDetail=()=>{const d=data.districts[selectedDistrict];return `<div class="district-detail"><h4>${esc(d[0])}</h4><p>${esc(d[1])}</p></div>`};
  const pages={
    home:()=>head('THE CREW','The Sneaks','A player-safe view of the crew and what has been shared at the table.')+`<div class="grid home-grid"><section class="panel crew-card"><div class="seal">♙</div><h3>${esc(data.crew.name)}</h3><p>Shadows crew · Quiet hands. Useful people. Problems become opportunities in the right light.</p><div class="stats"><div><small>CREW TYPE</small><b>${esc(data.crew.type)}</b></div><div><small>TIER</small><b>${esc(data.crew.tier)}</b></div><div><small>HOLD</small><b>${esc(data.crew.hold)}</b></div></div><p class="quote">“Same city. Different angle.”</p></section><section class="panel score-card"><p class="eyebrow">CURRENT SCORE</p><h3>${esc(data.score.title)}</h3><div class="quiet">${esc(data.score.detail)}</div><p class="muted">This page shows only score details deliberately shared with the crew.</p></section></div>`,
    score:()=>head('THE JOB','Current Score','Only the information the GM has made available to the crew.')+`<section class="panel score-card"><p class="eyebrow">GM-SHARED BRIEFING</p><h3>${esc(data.score.title)}</h3><div class="quiet">${esc(data.score.detail)}</div></section>`,
    map:()=>head('THE CITY','Known Doskvol','The whole city is visible. District details here stay broad, useful, and spoiler-free.')+`<section class="panel map-panel"><div class="map-canvas"><div class="districts">${data.districts.map((d,i)=>`<button class="${i===selectedDistrict?'active':''}" data-district="${i}">${esc(d[0])}</button>`).join('')}</div>${districtDetail()}</div></section>`,
    faces:()=>head('PEOPLE WHO MATTER','Known Faces','Only people the crew has met or been deliberately told about.')+`<section class="panel"><div class="face-grid">${data.faces.map(f=>`<article class="face"><div class="portrait">${esc(f.name[0])}</div><h3>${esc(f.name)}</h3><small>${esc(f.role)} · ${esc(f.place)}</small><p>${esc(f.desc)}</p><span class="status">${esc(f.tone)}</span></article>`).join('')}</div></section>`,
    factions:()=>head('THE CITY’S PRESSURE','Known Factions','The current relationship picture, without hidden agendas or GM notes.')+`<section class="panel"><ul class="list">${data.factions.map(f=>`<li><h3>${esc(f.name)}</h3><span class="status">${esc(f.status)}</span><p>${esc(f.desc)}</p></li>`).join('')}</ul></section>`,
    clues:()=>head('WHAT YOU KNOW','Clues & Information','Confirmed information the GM has shared with the crew.')+`<section class="panel">${data.clues.length?`<ul class="list">${data.clues.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`:'<div class="empty">No confirmed clues have been shared here yet.</div>'}</section>`,
    actions:()=>head('AT THE TABLE','Action Reference','A quick reminder of common approaches. Check your Blades sheet for your ratings and the full rules.')+`<section class="panel"><div class="action-grid">${[['Study','Learn or analyse.'],['Survey','Observe a situation.'],['Attune','Use arcane intuition.'],['Prowl','Move unseen.'],['Skirmish','Fight up close.'],['Sway','Influence someone.'],['Finesse','Handle something precisely.'],['Tinker','Build or repair.']].map(a=>`<article><b>${a[0]}</b><small>${a[1]}</small></article>`).join('')}</div></section>`
  };
  function render(){active=location.hash.slice(1)||active;if(!pages[active])active='home';$('#nav').innerHTML=nav.map(n=>`<button class="${active===n[0]?'active':''}" data-page="${n[0]}"><span>${n[1]}</span>${n[2]}</button>`).join('');$('#main').innerHTML=pages[active]();document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.page});document.querySelectorAll('[data-district]').forEach(b=>b.onclick=()=>{selectedDistrict=Number(b.dataset.district);render()});}
  window.addEventListener('hashchange',render);render();
})();
